Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2020-10, with the labels that each got.

#143 Update usage documentation for new CRD
  installation-usage.md
Labels: cncf-cla: yes, kind/documentation, lgtm, size/M

#139 Rename seccomp-operator to security-profiles-operator
  .golangci.yml
  CONTRIBUTING.md
  Dockerfile
  Makefile
  README.md
  api/v1alpha1/groupversion_info.go
  cloudbuild.yaml
  cmd/security-profiles-operator/main.go
  deploy/base/crd.yaml
  deploy/base/kustomization.yaml
  deploy/base/operator.yaml
  deploy/base/profiles/security-profiles-operator.json
  deploy/base/rbac.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  deploy/overlays/cluster/default-profiles.yaml
  deploy/overlays/cluster/kustomization.yaml
  deploy/overlays/cluster/operator-profile.yaml
  deploy/overlays/namespaced/daemonset.yaml
  deploy/overlays/namespaced/kustomization.yaml
  examples/pod.yaml
  examples/seccompprofile.yaml
  go.mod
  hack/pull-security-profiles-operator-build
  hack/pull-security-profiles-operator-build-image
  hack/pull-security-profiles-operator-test-e2e
  hack/pull-security-profiles-operator-test-unit
  hack/pull-security-profiles-operator-verify
  installation-usage.md
  internal/pkg/config/config.go
  internal/pkg/controllers/profile/profile.go
  internal/pkg/controllers/profile/profile_test.go
  release.md
  test/e2e_test.go
  test/suite_test.go
  test/tc_crd_example_profiles_test.go
  test/tc_default_profiles_test.go
  test/tc_invalid_profile_test.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/L

#144 Add Status field to SeccompProfile
  api/v1alpha1/seccompprofile_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  deploy/base/crd.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  internal/pkg/controllers/profile/profile.go
  internal/pkg/controllers/profile/profile_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#146 Fix SeccompProfile status RBAC
  deploy/base/rbac.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/S

#147 Update golangci-lint and enable linters
  .golangci.yml
  Makefile
  internal/pkg/version/version.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#148 Remove e2e build tag in favor of scoped tests
  Makefile
  test/e2e_test.go
  test/suite_test.go
  test/tc_default_profiles_test.go
  test/tc_redeploy_operator_test.go
  test/tc_run_pod_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S
