Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2020-11, with the labels that each got.

#151 Use osusergo build tag
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#149 Bump repo-infra version
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#153 Bump golang dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#154 Fix container image names
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  release.md
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#156 Bump version to v0.2.0
  VERSION
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/S

#158 Fix container image name for promotion location
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#157 Bump version to v0.3.0-dev
  VERSION
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#159 Update e2e kind cluster name
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#161 Add cmurphy as a reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#160 Bump dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M
