Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2020-12, with the labels that each got.

#162 Run e2e tests for namespaced deployment
  test/e2e_test.go
  test/tc_base_profiles_test.go
  test/tc_default_profiles_test.go
  test/tc_delete_profiles_test.go
  test/tc_redeploy_operator_test.go
  test/tc_run_pod_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#164 Allow setting linkmode in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#166 Add localhostProfile attribute and column
  api/v1alpha1/seccompprofile_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  deploy/base/crd.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  installation-usage.md
  internal/pkg/config/config.go
  internal/pkg/controllers/profile/profile.go
Labels: approved, cncf-cla: yes, kind/api-change, kind/documentation, kind/feature, lgtm, release-note, size/M

#165 Integrate selinux-operator into the SPO
  api/v1alpha1/selinuxpolicy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/security-profiles-operator/main.go
  deploy/base/crd.yaml
  deploy/base/operator.yaml
  deploy/base/rbac.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  examples/selinuxpolicy.yaml
  internal/pkg/controllers/selinuxpolicy/configmap_controller.go
  internal/pkg/controllers/selinuxpolicy/selinuxpolicy_controller.go
  internal/pkg/controllers/selinuxpolicy/setup.go
  internal/pkg/controllers/selinuxpolicy/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XXL

#171 Improve error messages and error handling
  internal/pkg/controllers/profile/profile.go
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, release-note-none, size/M

#170 Enable e2e tests to run on OpenShift
  Makefile
  deploy/base/operator.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  test/e2e_test.go
  test/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#172 Enable UBI-based image
  Makefile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XS

#173 Add UBI Dockerfiles
  Dockerfile.ubi
  Dockerfile.ubi.dockerignore
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#178 Reorganize CRD type definitions
  Makefile
  api/seccompprofile/v1alpha1/groupversion_info.go
  api/seccompprofile/v1alpha1/seccompprofile_types.go
  api/seccompprofile/v1alpha1/zz_generated.deepcopy.go
  api/selinuxpolicy/v1alpha1/groupversion_info.go
  api/selinuxpolicy/v1alpha1/selinuxpolicy_types.go
  api/selinuxpolicy/v1alpha1/zz_generated.deepcopy.go
  cmd/security-profiles-operator/main.go
  internal/pkg/controllers/profile/profile.go
  internal/pkg/controllers/profile/profile_test.go
  internal/pkg/controllers/selinuxpolicy/configmap_controller.go
  internal/pkg/controllers/selinuxpolicy/selinuxpolicy_controller.go
  internal/pkg/controllers/selinuxpolicy/setup.go
  test/e2e_test.go
  test/tc_default_profiles_test.go
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, release-note, size/L
