Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2020-08, with the labels that each got.

#53 Add resource limits
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/S

#54 Add default profile generation into operator deployment
  Makefile
  deploy/operator.yaml
  profiles/build.go
  profiles/nginx-1.19.1.json
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#55 Add default profile e2e test case
  deploy/operator.yaml
  internal/pkg/controllers/profile/profile.go
  internal/pkg/controllers/profile/profile_test.go
  profiles/build.go
  test/e2e_test.go
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/L

#57 Fix comment in e2e test
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#49 Watch all namespaces by default
  Usage.md
  cmd/seccomp-operator/main.go
  deploy/operator.yaml
  examples/profile.yaml
  internal/pkg/controllers/profile/profile.go
  internal/pkg/controllers/profile/profile_test.go
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/M

#58 Add example profile verification to e2e test
  test/e2e_test.go
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/M

#59 Fix permission issues when kubelet folder is set to 0700
  deploy/operator.yaml
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/M

#60 Enhance docs to reflect rootless deployment
  README.md
  installation-usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#61 Added nginx profile e2e test case
  examples/pod.yaml
  test/e2e_test.go
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/M

#62 Fix double symlink creation on operator restart
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#56 Add initial eventing machinery
  go.sum
  internal/pkg/controllers/profile/profile.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#67 Add e2e test to ensure operator can be cleaned up and redeployed
  Makefile
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/M

#71 Rename reconile variables to be more explicit
  internal/pkg/controllers/profile/profile.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#69 Update pull request template to match latest prow capabilities
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#68 Add gcr.io container image reference
  Makefile
  README.md
  deploy/operator.yaml
  test/e2e_test.go
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#70 Cleanup global consts and make GetProfilePath() public
  internal/pkg/controllers/profile/profile.go
  internal/pkg/controllers/profile/profile_test.go
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#72 Add basic seccomp profile validation
  internal/pkg/controllers/profile/profile.go
  internal/pkg/controllers/profile/profile_test.go
  internal/pkg/types/types.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#73 Fix local test-unit execution
  internal/pkg/controllers/profile/profile_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S

#74 Change imports paths to sigs.k8s.io
  Makefile
  cmd/seccomp-operator/main.go
  go.mod
  internal/pkg/controllers/profile/profile.go
  profiles/build.go
  test/e2e_test.go
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#75 Fix events RBAC and add e2e test
  deploy/operator.yaml
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/M

#78 Bump repo-infra and golangci-lint to latest version
  .golangci.yml
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#79 Add additional arches to seccomp profile type
  internal/pkg/types/types.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XS

#77 Initialize the operator with a dedicated subcommand
  cmd/seccomp-operator/main.go
  deploy/operator.yaml
  internal/pkg/config/config.go
  internal/pkg/controllers/profile/profile.go
  internal/pkg/controllers/profile/profile_test.go
  internal/pkg/initialize/initialize.go
  internal/pkg/initialize/initialize_test.go
  profiles/build.go
  test/e2e_test.go
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#80 Add support for Log (complain) mode
  internal/pkg/types/types.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XS

#83 Change from git inferred version to const version value
  Dockerfile
  Makefile
  cmd/seccomp-operator/main.go
  internal/pkg/version/version.go
  internal/pkg/version/version_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#84 Bump go modules and switch to klog/v2
  cmd/seccomp-operator/main.go
  go.mod
  go.sum
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#81 Revert init command and stick to simple bash image
  cmd/seccomp-operator/main.go
  deploy/operator.yaml
  internal/pkg/config/config.go
  internal/pkg/initialize/initialize.go
  internal/pkg/initialize/initialize_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#86 Remove internal seccomp types in favor of containers-golang package
  go.mod
  go.sum
  internal/pkg/controllers/profile/profile.go
  internal/pkg/types/types.go
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#87 Stop reconciling on invalid profile
  internal/pkg/controllers/profile/profile.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#88 Split-up e2e test into test cases
  test/e2e_test.go
  test/tc_default_profiles_test.go
  test/tc_invalid_profile_test.go
  test/tc_redeploy_operator_test.go
  test/tc_run_pod_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#91 Update k/release to 0.4.0 and make e2e test commands verbose
  go.mod
  go.sum
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XS

#90 Add new security context to example pod
  examples/pod.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/XS

#89 Verify that invalid profile gets not reconciled on disk
  test/e2e_test.go
  test/tc_default_profiles_test.go
  test/tc_invalid_profile_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#93 Validate that invalid profiles will be reconciled when patched
  test/tc_invalid_profile_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/M

#94 Re-enable restricting controller watch to single namespace
  cmd/seccomp-operator/main.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#95 Add support for deployment into master nodes
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XS

#96 Define nodeselector for linux os
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XS

#52 Add operator seccomp profile
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#85 Verify if nodes do support seccomp and do not reconcile in that case
  deploy/operator.yaml
  go.mod
  go.sum
  internal/pkg/config/config.go
  internal/pkg/controllers/profile/profile.go
  internal/pkg/node/seccomp/seccomp.go
  internal/pkg/node/seccomp/seccomp_test.go
  internal/pkg/node/seccomp/seccompfakes/fake_verifier.go
Labels: approved, cncf-cla: yes, kind/design, kind/feature, lgtm, release-note, size/XL

#97 Switch to golang 1.15
  Dockerfile
  go.mod
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#98 Use static VERSION file for version inject
  Dockerfile
  Makefile
  VERSION
  internal/pkg/version/version.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/S

#99 Update docs to reflect v1 feature set
  installation-usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#102 Bump release version to v0.1.0
  VERSION
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XS

#103 Bump release version to v0.2.0-dev
  VERSION
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XS

#110 Add Tutorials and Demos section to usage guide
  installation-usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#111 Switch to containers-golang seccomp check instead of internal
  go.mod
  go.sum
  internal/pkg/controllers/profile/profile.go
  internal/pkg/node/seccomp/seccomp.go
  internal/pkg/node/seccomp/seccomp_test.go
  internal/pkg/node/seccomp/seccompfakes/fake_verifier.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#112 Add monthly meeting to README.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#113 Add release process documentation
  README.md
  release.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#114 Use kustomize for deployment generation
  Makefile
  deploy/base/kustomization.yaml
  deploy/base/operator.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  deploy/overlays/namespaced/clusterrole.yaml
  deploy/overlays/namespaced/clusterrolebinding.yaml
  deploy/overlays/namespaced/configmap.yaml
  deploy/overlays/namespaced/daemonset.yaml
  deploy/overlays/namespaced/kustomization.yaml
  hack/pull-seccomp-operator-verify
  profiles/build.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XXL

#120 Switch to containers/common
  go.mod
  go.sum
  internal/pkg/controllers/profile/profile.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#122 Continue if a profile is invalid
  internal/pkg/controllers/profile/profile.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#123 Update Pod example for Kubernetes 1.19
  installation-usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/S

#124 Fix error messages
  internal/pkg/controllers/profile/profile.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S
