Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2020-09, with the labels that each got.

#128 Run e2e tests on k8s v1.19.0
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#129 Improve thrown events
  internal/pkg/controllers/profile/profile.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#130 Switch to logr v0.2.1
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#132 Update kind to v0.9.0
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#134 Bump dependencies
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#136 Add roadmap
  .github/mindmap.mup
  .github/mindmap.svg
  .github/roadmap.svg
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XXL
