Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2021-04, with the labels that each got.

#394 Use older ubuntu image for buildah-based builds
  .github/workflows/build.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#395 Remove leftover TODO
  internal/pkg/manager/nodestatus/nodestatus.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#393 Do not push main binary into cachix cache
  .github/workflows/build.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#386 Add recording webhook unit tests
  internal/pkg/webhooks/recording/impl.go
  internal/pkg/webhooks/recording/recording.go
  internal/pkg/webhooks/recording/recording_test.go
  internal/pkg/webhooks/recording/recordingfakes/fake_impl.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#396 Change SelinuxPolicy to SelinuxProfile
  Makefile
  api/profilebinding/v1alpha1/profilebinding_types.go
  api/selinuxprofile/v1alpha1/groupversion_info.go
  api/selinuxprofile/v1alpha1/selinuxpolicy_types.go
  api/selinuxprofile/v1alpha1/zz_generated.deepcopy.go
  cmd/security-profiles-operator/main.go
  deploy/base/crd.yaml
  deploy/base/role.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  examples/selinuxprofile.yaml
  internal/pkg/daemon/selinuxprofile/selinuxpolicy_controller.go
  internal/pkg/daemon/selinuxprofile/setup.go
  internal/pkg/daemon/selinuxprofile/utils.go
  internal/pkg/manager/nodestatus/nodestatus.go
  test/e2e_test.go
  test/tc_selinux_base_usage_test.go
Labels: approved, cncf-cla: yes, kind/api-change, kind/cleanup, lgtm, release-note, size/L

#399 Update nixpkgs
  nix/nixpkgs.json
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#400 Add mock-able profile binding implementation
  internal/pkg/webhooks/binding/binding.go
  internal/pkg/webhooks/binding/bindingfakes/fake_impl.go
  internal/pkg/webhooks/binding/impl.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#402 Add profile binding unit tests
  internal/pkg/webhooks/binding/binding.go
  internal/pkg/webhooks/binding/binding_test.go
  internal/pkg/webhooks/binding/bindingfakes/fake_impl.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XL

#404 Update kustomize to v4.1.2
  Makefile
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  deploy/webhook.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#403 Wrap retry error
  internal/pkg/util/retries.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#383 seccomp: Don't delete a profile in use
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/manager/workloadannotator/workloadannotator.go
  internal/pkg/util/constants.go
  test/e2e_test.go
  test/tc_delete_profiles_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#387 Install webhooks in main operator deployment
  Makefile
  deploy/base/certificate.yaml
  deploy/base/crds/profilebinding.yaml
  deploy/base/crds/profilerecording.yaml
  deploy/base/crds/seccompprofile.yaml
  deploy/base/crds/securityprofilenodestatus.yaml
  deploy/base/crds/securityprofilesoperatordaemon.yaml
  deploy/base/crds/selinuxpolicy.yaml
  deploy/base/kustomization.yaml
  deploy/base/manager_deployment.yaml
  deploy/base/mutatingwebhookconfig.yaml
  deploy/base/role.yaml
  deploy/base/role_binding.yaml
  deploy/base/service.yaml
  deploy/base/service_account.yaml
  deploy/base/webhook/role.yaml
  deploy/base/webhook/role_binding.yaml
  deploy/base/webhook/service_account.yaml
  deploy/base/webhook_deployment.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  hack/ci/e2e.sh
  installation-usage.md
  test/e2e_test.go
  test/suite_test.go
  test/tc_profilebindings_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#405 Move `toolg.go` into `internal/pkg`
  internal/pkg/tools/tools.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#406 SelinuxProfile: Remove apply flag from CRD
  api/selinuxprofile/v1alpha1/selinuxpolicy_types.go
  deploy/base/crd.yaml
  deploy/base/crds/selinuxpolicy.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  examples/selinuxprofile.yaml
  test/tc_selinux_base_usage_test.go
Labels: approved, cncf-cla: yes, kind/api-change, kind/cleanup, lgtm, release-note, size/S

#337 selinux: Use events in the selinux controller
  internal/pkg/daemon/selinuxprofile/selinuxpolicy_controller.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/S

#411 Run `make image` on ubuntu 18.04
  .github/workflows/test.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#412 Cleanup deployments and bump cert-manager
  deploy/base/webhook/kustomization.yaml
  deploy/webhook.yaml
  installation-usage.md
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XL

#414 Remove `custom-profiles` path within docs
  installation-usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/S

#415 Bump version to 0.3.0
  VERSION
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/S

#417 Bump version to 0.4.0-dev
  VERSION
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#416 Update release readme to match the current process
  release.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#419 Bump VM based e2e test to k8s v1.21.0
  hack/ci/install-kubernetes.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#420 Do not re-deploy cert-manager within e2e tests
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/L

#422 Add initial metrics support
  cmd/security-profiles-operator/main.go
  deploy/base/service.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  go.mod
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/selinuxprofile/setup.go
  internal/pkg/metrics/impl.go
  internal/pkg/metrics/metrics.go
  internal/pkg/metrics/metrics_test.go
  internal/pkg/metrics/metricsfakes/fake_impl.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XL

#426 Bump debian-base build image to buster-v1.6.0
  dependencies.yaml
  hack/build-image/Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#424 Add RBAC proxy to metrics
  cmd/security-profiles-operator/main.go
  dependencies.yaml
  deploy/base/kustomization.yaml
  deploy/base/metrics_client.yaml
  deploy/base/role.yaml
  deploy/base/service.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  internal/pkg/daemon/metrics/impl.go
  internal/pkg/daemon/metrics/metrics.go
  internal/pkg/daemon/metrics/metrics_test.go
  internal/pkg/daemon/metrics/metricsfakes/fake_impl.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/selinuxprofile/setup.go
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/spod_controller.go
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#427 Switch to sigs.k8s.io/release-utils
  go.mod
  go.sum
  internal/pkg/config/config.go
  internal/pkg/nonrootenabler/nonrootenabler.go
  test/e2e_test.go
  test/suite_test.go
  vendor/github.com/google/uuid/uuid.go
  vendor/k8s.io/release/LICENSE
  vendor/k8s.io/release/pkg/command/command.go
  vendor/k8s.io/release/pkg/command/global.go
  vendor/k8s.io/release/pkg/util/common.go
  vendor/k8s.io/release/pkg/util/env.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XXL
