Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2021-05, with the labels that each got.

#435 e2e: wait for seccomp profiles to be available
  test/e2e_test.go
  test/tc_profilerecordings_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/M

#436 Make profilerecording gathering more resilient
  internal/pkg/daemon/profilerecorder/profilerecorder.go
Labels: approved, cncf-cla: yes, kind/flake, lgtm, release-note-none, size/XS

#429 Merge metrics endpoints for using different paths
  cmd/security-profiles-operator/main.go
  deploy/base/metrics_client.yaml
  deploy/base/service.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  internal/pkg/daemon/metrics/metrics.go
  internal/pkg/daemon/metrics/metrics_test.go
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/spod_controller.go
Labels: approved, cncf-cla: yes, kind/design, kind/feature, lgtm, release-note-none, size/L

#438 Use systemd cgroup manager for e2e tests
  hack/ci/install-cri-o.sh
  hack/ci/install-kubernetes.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#437 Add controller interface for each SPOD controller
  cmd/security-profiles-operator/main.go
  internal/pkg/controller/controller.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/selinuxprofile/selinuxpolicy_controller.go
  internal/pkg/daemon/selinuxprofile/setup.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#430 Add liveness/startup probe to SPOD
  cmd/security-profiles-operator/main.go
  internal/pkg/atomic/bool.go
  internal/pkg/atomic/bool_test.go
  internal/pkg/config/config.go
  internal/pkg/controller/controller.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/selinuxprofile/selinuxpolicy_controller.go
  internal/pkg/manager/spod/bindata/spod.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#444 Add manager controllers to `Controller` interface
  cmd/security-profiles-operator/main.go
  internal/pkg/controller/controller.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/selinuxprofile/setup.go
  internal/pkg/manager/nodestatus/nodestatus.go
  internal/pkg/manager/nodestatus/setup.go
  internal/pkg/manager/spod/setup.go
  internal/pkg/manager/spod/setup_test.go
  internal/pkg/manager/spod/spod_controller.go
  internal/pkg/manager/workloadannotator/setup.go
  internal/pkg/manager/workloadannotator/workloadannotator.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#428 Add metrics e2e test
  test/e2e_test.go
  test/suite_test.go
  test/tc_metrics_test.go
  test/tc_profilerecordings_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#446 Update golangci-lint to v1.40.1 and fix lints
  .golangci.yml
  Makefile
  dependencies.yaml
  internal/pkg/daemon/metrics/metrics.go
  internal/pkg/manager/workloadannotator/workloadannotator.go
  test/tc_metrics_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#448 Add link to KubeCon Europe talk
  installation-usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#449 Add metrics documentation
  installation-usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/M

#451 Use single TLS certificate/key for serving metrics
  deploy/base/certificate.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  installation-usage.md
  internal/pkg/manager/spod/bindata/spod.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#455 Update kind to v0.11.0
  dependencies.yaml
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#458 Add default ServiceMonitor if the CRD is available
  cmd/security-profiles-operator/main.go
  deploy/base/role.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  internal/pkg/manager/spod/bindata/servicemonitor.go
  internal/pkg/manager/spod/spod_controller.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/go.mod
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/go.sum
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#456 Add name=spod label to metrics service
  deploy/base/service.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XS

#457 Add metrics-token secret to deployment
  deploy/base/metrics_client.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#460 Add ServiceMonitor documentation
  doc/img/openshift-metrics.png
  doc/img/prometheus-targets.png
  installation-usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/M

#447 Simplify zeitgeist matches
  dependencies.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#461 Add seccomp error metrics
  installation-usage.md
  internal/pkg/daemon/metrics/metrics.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/seccompprofile/seccompprofile_test.go
  test/tc_metrics_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#465 Bump kind to v0.11.1
  dependencies.yaml
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS
