Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2021-11, with the labels that each got.

#630 Add arm64 support for bpf recorder
  .github/workflows/build.yml
  Makefile
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/generate/main.go
  internal/pkg/daemon/bpfrecorder/generated.go
  internal/pkg/daemon/bpfrecorder/vmlinux/arm64/5.11.12-300.fc34.aarch64.vmlinux.h
  internal/pkg/daemon/bpfrecorder/vmlinux/arm64/vmlinux.h
  internal/pkg/daemon/bpfrecorder/vmlinux/x86/5.11.12-300.fc34.x86_64.vmlinux.h
  internal/pkg/daemon/bpfrecorder/vmlinux/x86/vmlinux.h
  nix/default-bpf-arm64.nix
  nix/derivation-bpf.nix
  nix/derivation.nix
Labels: kind/feature, size/XXL, cncf-cla: yes, lgtm, release-note-none, approved

#634 Reference the bindata container ID as const
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/spod_controller.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#633 Remove no_bpf build tag
  .github/workflows/test.yml
  .golangci.yml
  Dockerfile.ubi
  Makefile
  dependencies.yaml
  go.mod
  go.sum
  hack/install-libbpf.sh
  hack/install-libelf.sh
  hack/pull-security-profiles-operator-build
  hack/pull-security-profiles-operator-test-unit
  hack/pull-security-profiles-operator-verify
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_unsupported.go
  internal/pkg/daemon/bpfrecorder/generate/main.go
  internal/pkg/daemon/bpfrecorder/generated.go
  vendor/github.com/aquasecurity/libbpfgo/Readme.md
  vendor/github.com/aquasecurity/libbpfgo/libbpf_cb.go
  vendor/github.com/aquasecurity/libbpfgo/libbpfgo.go
  vendor/modules.txt
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#635 Rely on BPF PID tracking rather than mount namespaces
  .golangci.yml
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.c
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/generated.go
Labels: kind/bug, size/XXL, cncf-cla: yes, lgtm, release-note-none, approved

#636 Upgrade fedora to 35
  dependencies.yaml
  hack/ci/Vagrantfile-fedora
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#638 Make cgroup tracking more robust
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/manager/workloadannotator/workloadannotator.go
  internal/pkg/util/containers.go
  internal/pkg/util/names.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#637 Reuse util.ContainerIDForPID in enricher
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/enricher/enricherfakes/fake_impl.go
  internal/pkg/daemon/enricher/impl.go
  internal/pkg/util/containers_test.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#641 enricher: Remove useless Info-level log line
  internal/pkg/daemon/enricher/enricher.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#639 Add bpf recorder unit tests
  Makefile
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/bpfrecorder/bpfrecorderfakes/fake_impl.go
  internal/pkg/daemon/bpfrecorder/generate/main.go
  internal/pkg/daemon/bpfrecorder/impl.go
Labels: size/XXL, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#640 selinux: Don't emit errors or events if we're only waiting for selinuxd to remove policy
  internal/pkg/daemon/selinuxprofile/selinuxpolicy_controller.go
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#631 Switch to GRPC sockets rather than using tcp ports
  internal/pkg/config/config.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorderfakes/fake_impl.go
  internal/pkg/daemon/bpfrecorder/impl.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/enricher/enricherfakes/fake_impl.go
  internal/pkg/daemon/enricher/impl.go
  internal/pkg/daemon/metrics/grpc.go
  internal/pkg/manager/spod/bindata/spod.go
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, lgtm, approved

#644 Add more recorder unit tests
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/bpfrecorder/bpfrecorderfakes/fake_impl.go
  internal/pkg/daemon/bpfrecorder/impl.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#643 Create draft version of AppArmor CRD
  api/apparmorprofile/v1alpha1/apparmorprofile_types.go
  api/apparmorprofile/v1alpha1/groupversion_info.go
  api/apparmorprofile/v1alpha1/zz_generated.deepcopy.go
  deploy/base/crds/apparmorprofiles.yaml
  examples/apparmorprofile.yaml
Labels: kind/feature, size/L, release-note, cncf-cla: yes, kind/api-change, lgtm, approved

#646 Use mount namespace for faster tracking
  .github/workflows/build.yml
  Makefile
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.c
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/bpfrecorder/bpfrecorderfakes/fake_impl.go
  internal/pkg/daemon/bpfrecorder/generated.go
  internal/pkg/daemon/bpfrecorder/impl.go
Labels: kind/feature, size/XXL, cncf-cla: yes, lgtm, release-note-none, approved

#647 Add host PID hint and clarify syscall_id var
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.c
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/generated.go
Labels: size/XXL, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#648 Add start/stop unit tests for BPF recorder
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#650 apparmor: add initial AppArmor CRD management implementation
  api/apparmorprofile/v1alpha1/apparmorprofile_types.go
  deploy/base/crds/apparmorprofile.yaml
  deploy/base/kustomization.yaml
  deploy/base/role.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  examples/apparmorprofile.yaml
  internal/pkg/daemon/apparmorprofile/apparmor.go
  internal/pkg/daemon/apparmorprofile/apparmorprofile.go
  internal/pkg/daemon/metrics/metrics.go
Labels: kind/feature, cncf-cla: yes, size/XL, lgtm, release-note-none, approved

#645 Suppress one linter issue
  test/tc_profilerecordings_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#654 Add CII Best Practices badge
  README.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/documentation

#655 Bump golang.org/x/text to v0.3.7
  go.mod
  go.sum
  vendor/modules.txt
Labels: release-note, cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup

#652 Add features and their status
  README.md
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/documentation

#661 Add bpf recorder e2e test
  hack/ci/e2e-fedora.sh
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  test/e2e_test.go
  test/suite_test.go
  test/tc_bpf_recorder_test.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#657 Make log verbosity usable
  cmd/security-profiles-operator/main.go
Labels: kind/feature, release-note, cncf-cla: yes, size/S, lgtm, approved

#658 Reduce verbose level to `1`
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#664 Update the SELinux policy for selinuxd to support F-35
  deploy/base/profiles/selinuxd.cil
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#665 Add `Verbosity` option to spod config
  api/spod/v1alpha1/spod_types.go
  cmd/security-profiles-operator/main.go
  deploy/base/crds/securityprofilesoperatordaemon.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  installation-usage.md
  internal/pkg/config/config.go
  internal/pkg/manager/spod/setup.go
  internal/pkg/manager/spod/spod_controller.go
  test/e2e_test.go
  test/tc_verbosity_test.go
Labels: kind/feature, release-note, cncf-cla: yes, lgtm, approved, size/M

#656 Filter system mount namespace
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#663 Early give-up on short-lived processes
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/bpfrecorder/impl.go
  internal/pkg/daemon/bpfrecorder/vars.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/M

#666 Add bpf recorder metrics
  api/grpc/metrics/api.pb.go
  api/grpc/metrics/api.proto
  api/grpc/metrics/api_grpc.pb.go
  installation-usage.md
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/bpfrecorder/bpfrecorderfakes/fake_impl.go
  internal/pkg/daemon/bpfrecorder/impl.go
  internal/pkg/daemon/metrics/grpc.go
  internal/pkg/daemon/metrics/metrics.go
  internal/pkg/daemon/metrics/metrics_test.go
  test/tc_bpf_recorder_test.go
Labels: kind/feature, cncf-cla: yes, size/XL, lgtm, release-note-none, approved

#669 Update to nix 2.4 and nixpkgs
  Dockerfile.build-image
  Makefile
  dependencies.yaml
  internal/pkg/daemon/bpfrecorder/generated.go
  nix/derivation-bpf.nix
  nix/nixpkgs.json
Labels: size/XXL, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#671 Make seccomp profile architectures non pointers
  api/seccompprofile/v1alpha1/seccompprofile_types.go
  api/seccompprofile/v1alpha1/zz_generated.deepcopy.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/manager/spod/bindata/default_profiles.go
Labels: release-note, cncf-cla: yes, kind/api-change, size/S, lgtm, approved

#670 Add architecture to recorded seccomp profiles
  api/grpc/bpfrecorder/api.pb.go
  api/grpc/bpfrecorder/api.proto
  api/grpc/enricher/api.pb.go
  api/grpc/enricher/api.proto
  api/grpc/metrics/api_grpc.pb.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/enricher/grpc.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
Labels: kind/feature, size/L, release-note, cncf-cla: yes, lgtm, approved

#673 Add BPF recorder docs
  installation-usage.md
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation

#678 e2e: Add SELinux recording test of a deployment
  test/e2e_test.go
  test/tc_profilerecordings_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#681 Add update-vmlinux makefile target
  Makefile
  dependencies.yaml
  hack/update-vmlinux
  internal/pkg/daemon/bpfrecorder/generated.go
  internal/pkg/daemon/bpfrecorder/vmlinux/arm64/5.14.10-300.fc35.aarch64.vmlinux.h
  internal/pkg/daemon/bpfrecorder/vmlinux/arm64/vmlinux.h
  internal/pkg/daemon/bpfrecorder/vmlinux/x86/5.14.10-300.fc35.x86_64.vmlinux.h
  internal/pkg/daemon/bpfrecorder/vmlinux/x86/vmlinux.h
Labels: size/XXL, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#683 Allow fetching running spod name from within it
  internal/pkg/config/config.go
  internal/pkg/daemon/common/common.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/spod_controller.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#682 Update repo-infra to v0.2.3
  Makefile
  dependencies.yaml
  internal/pkg/daemon/bpfrecorder/bpfrecorderfakes/fake_impl.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#684 tests: Don't wait for all pods in all namespaces when testing against an OpenShift cluster
  test/e2e_test.go
  test/suite_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#688 Ignore make update-btf failures
  .github/workflows/build.yml
Labels: kind/bug, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#694 Selinux CRD: Fix year in copyright comment
  api/selinuxprofile/v1alpha2/common.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#698 spod: Make /etc/selinux.d an emptyDir instead of hostPath
  internal/pkg/manager/spod/bindata/spod.go
Labels: release-note, cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup

#692 Improve fedora-e2e flakeness
  .github/workflows/test.yml
  hack/ci/Vagrantfile-fedora
  test/suite_test.go
Labels: kind/bug, cncf-cla: yes, kind/flake, size/S, lgtm, release-note-none, approved

#700 Add first profilerecorder unit tests
  Makefile
  internal/pkg/daemon/profilerecorder/impl.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/profilerecorder/profilerecorder_test.go
  internal/pkg/daemon/profilerecorder/profilerecorderfakes/fake_impl.go
Labels: cncf-cla: yes, size/XL, lgtm, release-note-none, approved, kind/cleanup

#697 SELinux: Add health probe
  internal/pkg/daemon/selinuxprofile/common_controller.go
Labels: kind/feature, cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#702 Make short running containers work with bpf recorder
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  test/e2e_test.go
  test/tc_bpf_recorder_test.go
Labels: kind/feature, size/L, cncf-cla: yes, lgtm, release-note-none, approved

#703 Mark profile generation with ebpf as supported
  README.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/documentation

#701 Add parallel bpf recording e2e test
  test/e2e_test.go
  test/tc_bpf_recorder_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#693 Initial Security Model
  README.md
  security-model.md
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation

#704 Retry syscall for PID retrieval in bpf recorder
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#705 Add unit test for system mount namespace skip
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#706 Rename `master` references to `main`
  .github/workflows/build.yml
  .github/workflows/test.yml
  hack/ci/install-cri-o.sh
  installation-usage.md
  release.md
Labels: release-note, cncf-cla: yes, size/S, lgtm, approved, kind/documentation

#707 selinux: Fix selinuxd policy for RHEL-8/CentoOS-8/RHCOS
  deploy/base/profiles/selinuxd.cil
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift.yaml
  deploy/operator.yaml
Labels: cncf-cla: yes, kind/regression, size/S, lgtm, release-note-none, approved

#710 Add more profilerecorder unit tests
  internal/pkg/daemon/profilerecorder/impl.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/profilerecorder/profilerecorder_test.go
  internal/pkg/daemon/profilerecorder/profilerecorderfakes/fake_impl.go
Labels: size/XXL, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#711 Update name of `osrelease` dependency
  go.mod
  go.sum
  internal/pkg/daemon/bpfrecorder/impl.go
  vendor/github.com/acobaugh/osrelease/.travis.yml
  vendor/github.com/acobaugh/osrelease/LICENSE
  vendor/github.com/acobaugh/osrelease/README.md
  vendor/github.com/acobaugh/osrelease/osrelease.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/S, ok-to-test, lgtm, release-note-none, approved, kind/cleanup

#709 Enhance SELinux profile validation
  internal/pkg/daemon/selinuxprofile/selinuxprofile.go
  internal/pkg/daemon/selinuxprofile/selinuxprofile_test.go
Labels: kind/bug, size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#685 secprofnodestatus: Link the node profile status with profile using a custom label
  api/secprofnodestatus/v1alpha1/secprofnodestatus_types.go
  internal/pkg/manager/nodestatus/nodestatus.go
  internal/pkg/nodestatus/nodestatus.go
  internal/pkg/util/names.go
  internal/pkg/util/names_test.go
  test/e2e_test.go
  test/tc_long_profile_name_test.go
Labels: size/L, release-note, cncf-cla: yes, lgtm, approved, kind/cleanup

#720 Switch to codecov v2 GH action
  .github/workflows/test.yml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#721 Add codecov badge
  README.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/documentation

#690 Make BPF optional again
  Dockerfile.ubi
  Makefile
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_unsupported.go
  internal/pkg/daemon/bpfrecorder/bpfrecorderfakes/fake_impl.go
  internal/pkg/daemon/bpfrecorder/generate/main.go
  internal/pkg/daemon/bpfrecorder/generated.go
  internal/pkg/daemon/bpfrecorder/impl.go
Labels: kind/feature, release-note, cncf-cla: yes, lgtm, approved, size/M

#719 Finish profilerecorder unit tests
  internal/pkg/daemon/profilerecorder/impl.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/profilerecorder/profilerecorder_test.go
  internal/pkg/daemon/profilerecorder/profilerecorderfakes/fake_impl.go
Labels: size/XXL, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#726 Bump kustomize to v4.4.1
  Makefile
  dependencies.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#729 images: use k8s-staging-test-infra/gcb-docker-gcloud
  cloudbuild.yaml
  dependencies.yaml
Labels: cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, size/XS

#730 images: fix invalid k8s-staging-test-infra/gcb-docker-gcloud tag
  cloudbuild.yaml
  dependencies.yaml
Labels: cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, size/XS
