Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2021-10, with the labels that each got.

#601 selinux: Remove dead code
  internal/pkg/daemon/selinuxprofile/selinuxpolicy_controller.go
  internal/pkg/daemon/selinuxprofile/utils.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#600 Add jhrozek and JAORMX as approvers
  OWNERS
Labels: kind/feature, cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#606 Update mdtoc to v1.1.0
  go.mod
  go.sum
  installation-usage.md
  vendor/github.com/gomarkdown/markdown/ast/node.go
  vendor/github.com/gomarkdown/markdown/html/callouts.go
  vendor/github.com/gomarkdown/markdown/html/doc.go
  vendor/github.com/gomarkdown/markdown/html/esc.go
  vendor/github.com/gomarkdown/markdown/html/renderer.go
  vendor/github.com/gomarkdown/markdown/parser/block.go
  vendor/modules.txt
  vendor/sigs.k8s.io/mdtoc/.gitignore
  vendor/sigs.k8s.io/mdtoc/.golangci.yml
  vendor/sigs.k8s.io/mdtoc/Makefile
  vendor/sigs.k8s.io/mdtoc/OWNERS_ALIASES
  vendor/sigs.k8s.io/mdtoc/go.mod
  vendor/sigs.k8s.io/mdtoc/go.sum
  vendor/sigs.k8s.io/mdtoc/mdtoc.go
  vendor/sigs.k8s.io/mdtoc/pkg/mdtoc/mdtoc.go
Labels: release-note, cncf-cla: yes, size/XL, lgtm, approved, kind/documentation

#607 webhook: Remove unneeded RBAC permission from the recording webhook
  internal/pkg/webhooks/recording/recording.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup
