Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2021-12, with the labels that each got.

#728 Update cert-manager to v1.6.1
  Makefile
  dependencies.yaml
  installation-usage.md
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#732 Sort auto-generated CRDs
  Makefile
  dependencies.yaml
  deploy/base/crds/profilebinding.yaml
  deploy/base/crds/profilerecording.yaml
  deploy/base/crds/seccompprofile.yaml
  deploy/base/crds/securityprofilenodestatus.yaml
  deploy/base/crds/securityprofilesoperatordaemon.yaml
  deploy/base/crds/selinuxpolicy.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift.yaml
  deploy/operator.yaml
  hack/sort-crds.sh
Labels: kind/bug, cncf-cla: yes, size/XL, kind/failing-test, lgtm, release-note-none, approved

#724 Bump kube-rbac-proxy to v0.11.0
  dependencies.yaml
  internal/pkg/manager/spod/bindata/spod.go
Labels: kind/feature, release-note, cncf-cla: yes, lgtm, approved, size/XS

#734 Bump nixpkgs
  nix/nixpkgs.json
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#723 Bump e2e test k8s to v1.22.4
  .github/workflows/test.yml
  dependencies.yaml
  hack/ci/Vagrantfile-ubuntu
  hack/ci/install-kubernetes.sh
  test/suite_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#735 Limit bpf recorder ttl cache size
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorderfakes/fake_impl.go
  internal/pkg/daemon/bpfrecorder/impl.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#737 Remove unecessary token permissions
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#741 Pin container base images
  Dockerfile
  Dockerfile.build-image
  Dockerfile.ubi
  dependencies.yaml
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#739 Fix codeql workflow permissions
  .github/workflows/test.yml
Labels: cncf-cla: yes, kind/regression, lgtm, release-note-none, approved, size/XS, kind/cleanup

#738 Bump and pin github actions' dependencies
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#742 Show libbpf version in `version` subcommand
  dependencies.yaml
  internal/pkg/version/version.go
  internal/pkg/version/version_bpf_supported.go
  internal/pkg/version/version_bpf_unsupported.go
  internal/pkg/version/version_seccomp_supported.go
  internal/pkg/version/version_seccomp_unsupported.go
  internal/pkg/version/version_test.go
Labels: kind/feature, release-note, cncf-cla: yes, lgtm, approved, size/M

#745 Limit log enricher ttl cache size
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricherfakes/fake_impl.go
  internal/pkg/daemon/enricher/impl.go
Labels: kind/feature, cncf-cla: yes, lgtm, release-note-none, approved, size/M

#746 Add profiling endpoint support
  api/spod/v1alpha1/spod_types.go
  cmd/security-profiles-operator/main.go
  deploy/base/crds/securityprofilesoperatordaemon.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift.yaml
  deploy/operator.yaml
  installation-usage.md
  internal/pkg/config/config.go
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/spod_controller.go
Labels: kind/feature, size/L, release-note, cncf-cla: yes, lgtm, approved

#747 Make bpf kubectl run test more robust
  test/tc_bpf_recorder_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#748 Increase ephemeral storage for log-enricher
  internal/pkg/manager/spod/bindata/spod.go
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#750 Switch to using quay.io/security-profiles-operator/selinuxd
  deploy/base/kustomization.yaml
  deploy/base/manager_deployment.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift.yaml
  deploy/operator.yaml
  internal/pkg/manager/spod/bindata/spod.go
  test/suite_test.go
Labels: release-note, cncf-cla: yes, size/S, lgtm, approved, kind/cleanup

#749 Pin cri-o and redhat-actions/push-to-registry
  .github/workflows/build.yml
  hack/ci/install-cri-o.sh
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#751 Increase maximum log enricher memory to 256MiB
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/manager/spod/bindata/spod.go
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#753 Fix typo in selinux recording example
  examples/profilerecording-selinux-logs.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#761 selinux: Enable the selinuxd profiling endpoint with enableProfiling=true
  installation-usage.md
  internal/pkg/manager/spod/spod_controller.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#762 Bump to v0.4.0
  VERSION
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift.yaml
  deploy/operator.yaml
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/documentation

#763 Switch back to dev VERSION
  VERSION
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift.yaml
  deploy/operator.yaml
  release.md
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#764 Increase manager memory constraints
  deploy/base/manager_deployment.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift.yaml
  deploy/operator.yaml
Labels: kind/bug, release-note, cncf-cla: yes, size/S, lgtm, approved
