Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2021-07, with the labels that each got.

#509 Cache pods and container IDs in log enricher
  go.mod
  go.sum
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  vendor/github.com/ReneKroon/ttlcache/v2/.travis.yml
  vendor/github.com/ReneKroon/ttlcache/v2/CHANGELOG.md
  vendor/github.com/ReneKroon/ttlcache/v2/LICENSE
  vendor/github.com/ReneKroon/ttlcache/v2/Readme.md
  vendor/github.com/ReneKroon/ttlcache/v2/cache.go
  vendor/github.com/ReneKroon/ttlcache/v2/evictionreason_enumer.go
  vendor/github.com/ReneKroon/ttlcache/v2/go.mod
  vendor/github.com/ReneKroon/ttlcache/v2/go.sum
  vendor/github.com/ReneKroon/ttlcache/v2/item.go
  vendor/github.com/ReneKroon/ttlcache/v2/metrics.go
  vendor/github.com/ReneKroon/ttlcache/v2/priority_queue.go
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#514 Deflake metrics e2e test
  test/suite_test.go
  test/tc_metrics_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S

#515 Update kustomize to v4.2.0
  Makefile
  dependencies.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#513 Add support for log enricher profile recording
  .golangci.yml
  api/profilerecording/v1alpha1/profilerecording_types.go
  api/server/api.pb.go
  api/server/api.proto
  api/server/api_grpc.pb.go
  deploy/base/crds/profilerecording.yaml
  deploy/base/webhook_deployment.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  examples/profilerecording-hook.yaml
  examples/profilerecording-logs.yaml
  hack/deploy-localhost.patch
  internal/pkg/config/config.go
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/enricher/enricherfakes/fake_impl.go
  internal/pkg/daemon/enricher/impl.go
  internal/pkg/daemon/enricher/types.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/server/server.go
  internal/pkg/manager/spod/bindata/default_profiles.go
  internal/pkg/webhooks/recording/recording.go
  internal/pkg/webhooks/recording/recording_test.go
  test/e2e_test.go
  test/tc_profilerecordings_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#518 Switch from github.com/hpcloud/tail to github.com/nxadm/tail
  go.mod
  go.sum
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/enricher/enricherfakes/fake_impl.go
  internal/pkg/daemon/enricher/impl.go
  vendor/github.com/hpcloud/tail/.gitignore
  vendor/github.com/hpcloud/tail/.travis.yml
  vendor/github.com/hpcloud/tail/CHANGES.md
  vendor/github.com/hpcloud/tail/Dockerfile
  vendor/github.com/hpcloud/tail/Makefile
  vendor/github.com/hpcloud/tail/README.md
  vendor/github.com/hpcloud/tail/appveyor.yml
  vendor/github.com/hpcloud/tail/tail_posix.go
  vendor/github.com/hpcloud/tail/tail_windows.go
  vendor/github.com/nxadm/tail/.gitignore
  vendor/github.com/nxadm/tail/CHANGES.md
  vendor/github.com/nxadm/tail/Dockerfile
  vendor/github.com/nxadm/tail/LICENSE
  vendor/github.com/nxadm/tail/README.md
  vendor/github.com/nxadm/tail/go.mod
  vendor/github.com/nxadm/tail/go.sum
  vendor/github.com/nxadm/tail/ratelimiter/Licence
  vendor/github.com/nxadm/tail/ratelimiter/leakybucket.go
  vendor/github.com/nxadm/tail/ratelimiter/memory.go
  vendor/github.com/nxadm/tail/ratelimiter/storage.go
  vendor/github.com/nxadm/tail/tail.go
  vendor/github.com/nxadm/tail/tail_posix.go
  vendor/github.com/nxadm/tail/tail_windows.go
  vendor/github.com/nxadm/tail/util/util.go
  vendor/github.com/nxadm/tail/watch/filechanges.go
  vendor/github.com/nxadm/tail/watch/inotify.go
  vendor/github.com/nxadm/tail/watch/inotify_tracker.go
  vendor/github.com/nxadm/tail/watch/polling.go
  vendor/github.com/nxadm/tail/watch/watch.go
  vendor/github.com/nxadm/tail/winfile/winfile.go
  vendor/gopkg.in/fsnotify.v1/.editorconfig
  vendor/gopkg.in/fsnotify.v1/.gitignore
  vendor/gopkg.in/fsnotify.v1/.travis.yml
  vendor/gopkg.in/fsnotify.v1/AUTHORS
  vendor/gopkg.in/fsnotify.v1/CHANGELOG.md
  vendor/gopkg.in/fsnotify.v1/CONTRIBUTING.md
  vendor/gopkg.in/fsnotify.v1/LICENSE
  vendor/gopkg.in/fsnotify.v1/README.md
  vendor/gopkg.in/fsnotify.v1/fen.go
  vendor/gopkg.in/fsnotify.v1/fsnotify.go
  vendor/gopkg.in/fsnotify.v1/inotify.go
  vendor/gopkg.in/fsnotify.v1/inotify_poller.go
  vendor/gopkg.in/fsnotify.v1/kqueue.go
  vendor/gopkg.in/fsnotify.v1/open_mode_bsd.go
  vendor/gopkg.in/fsnotify.v1/open_mode_darwin.go
  vendor/gopkg.in/fsnotify.v1/windows.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XXL

#521 Add docs about log enricher recordings
  installation-usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/L

#520 Enhance enricher e2e tests
  test/e2e_test.go
  test/tc_profilerecordings_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#519 Add streaming support for enricher metrics
  api/server/api.pb.go
  api/server/api.proto
  api/server/api_grpc.pb.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/enricher/enricherfakes/fake_impl.go
  internal/pkg/daemon/enricher/impl.go
  internal/pkg/daemon/server/server.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#522 Streamline container ID retrieval
  internal/pkg/daemon/enricher/audit.go
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/container_test.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/types.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#526 Update golangci lint and fix issues
  .golangci.yml
  Makefile
  cmd/security-profiles-operator/main.go
  dependencies.yaml
  internal/pkg/daemon/selinuxprofile/selinuxpolicy_controller.go
  internal/pkg/manager/nodestatus/nodestatus.go
  internal/pkg/version/version.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#517 Add streaming support for syscall recording
  api/server/api.pb.go
  api/server/api.proto
  api/server/api_grpc.pb.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricherfakes/fake_impl.go
  internal/pkg/daemon/enricher/impl.go
  internal/pkg/daemon/server/server.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/L

#523 Bump nixpkgs to retrieve the latest build dependencies
  nix/nixpkgs.json
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#524 Add libseccomp version to version command
  go.mod
  internal/pkg/version/version.go
  internal/pkg/version/version_supported.go
  internal/pkg/version/version_unsupported.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#525 Fix log enricher recording link
  installation-usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#527 Add more enricher unit tests
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/enricher/enricherfakes/fake_impl.go
  internal/pkg/daemon/enricher/impl.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#530 Bump cert-manager to v1.4.0
  dependencies.yaml
  installation-usage.md
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#531 Add syslog support to log enricher
  installation-usage.md
  internal/pkg/config/config.go
  internal/pkg/daemon/enricher/audit_test.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/manager/spod/bindata/spod.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#533 Preserve reason if tail fails
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/enricher/enricherfakes/fake_impl.go
  internal/pkg/daemon/enricher/impl.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#537 Always use root user for log-enricher
  internal/pkg/manager/spod/bindata/spod.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#538 Add ubuntu based e2e tests for log enricher
  .github/workflows/build.yml
  .github/workflows/test.yml
  Makefile
  dependencies.yaml
  hack/ci/Vagrantfile-fedora
  hack/ci/Vagrantfile-ubuntu
  hack/ci/e2e-fedora.sh
  hack/ci/e2e-ubuntu.sh
  hack/ci/env-fedora.sh
  hack/ci/env-ubuntu.sh
  hack/ci/install-kubernetes.sh
  hack/ci/run-fedora.sh
  hack/ci/run-ubuntu.sh
  installation-usage.md
  internal/pkg/daemon/enricher/container_test.go
  test/e2e_test.go
  test/tc_log_enricher_test.go
  test/tc_profilebindings_test.go
  test/tc_profilerecordings_test.go
  test/tc_redeploy_operator_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#536 Use context for GRPC client connection
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/enricher/enricherfakes/fake_impl.go
  internal/pkg/daemon/enricher/impl.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/server/server.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#535 Check for correct enricher pod state in e2e test
  test/tc_log_enricher_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S

#543 Update baseprofiles to recent versions
  examples/baseprofile-crun.yaml
  examples/baseprofile-runc.yaml
  installation-usage.md
  test/tc_base_profiles_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#539 Add arm64 support for syscall names
  .golangci.yml
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/syscall_amd64.go
  internal/pkg/daemon/enricher/syscall_arm64.go
  internal/pkg/daemon/enricher/types.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#548 Fix 'unsupported platform' typo
  internal/pkg/daemon/enricher/syscall_unsupported.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#546 Retry GRPC connection in enricher
  internal/pkg/daemon/enricher/enricher.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#549 Use -trimpath for builds
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#551 Update cert-manager to v1.4.1
  dependencies.yaml
  installation-usage.md
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#550 Add resource requests/limits to manager and webhook
  deploy/base/manager_deployment.yaml
  deploy/base/webhook_deployment.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  internal/pkg/manager/spod/bindata/spod.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#552 selinux: Print diagnostic message from selinuxd in event on failure
  internal/pkg/daemon/selinuxprofile/selinuxpolicy_controller.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#555 Label dependabot PRs `ok-to-test`
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#556 Add missing libseccomp version to init log
  cmd/security-profiles-operator/main.go
  internal/pkg/version/version.go
  internal/pkg/version/version_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/S
