Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2021-06, with the labels that each got.

#470 Add Metrics for SELinux profiles
  installation-usage.md
  internal/pkg/daemon/metrics/metrics.go
  internal/pkg/daemon/metrics/metrics_test.go
  internal/pkg/daemon/selinuxprofile/selinuxpolicy_controller.go
  internal/pkg/daemon/selinuxprofile/setup.go
  test/e2e_test.go
  test/suite_test.go
  test/tc_metrics_test.go
  test/tc_selinux_base_usage_test.go
  test/tc_selinux_sanity_check_test.go
  test/tc_spod_update_selinux_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#477 Cleanup log-enricher implementation
  cmd/security-profiles-operator/main.go
  internal/pkg/config/config.go
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/spod_controller.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#478 Add localhost deployment patch
  hack/deploy-localhost.patch
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#480 Deflake e2e tests
  hack/ci/Vagrantfile
  hack/ci/env.sh
  test/e2e_test.go
  test/suite_test.go
  test/tc_metrics_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/M

#482 Add comments about single node setup
  hack/ci/Vagrantfile
  hack/ci/env.sh
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#479 Fix log enricher read and automatically add `/dev/kmsg` device
  internal/pkg/config/config.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/manager/spod/bindata/spod.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#481 Bump repo-infra to v0.1.8
  Makefile
  dependencies.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#487 Switch to auditd logs for log enricher
  go.mod
  go.sum
  internal/pkg/config/config.go
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/manager/spod/bindata/spod.go
  vendor/github.com/hpcloud/tail/.gitignore
  vendor/github.com/hpcloud/tail/.travis.yml
  vendor/github.com/hpcloud/tail/CHANGES.md
  vendor/github.com/hpcloud/tail/Dockerfile
  vendor/github.com/hpcloud/tail/LICENSE.txt
  vendor/github.com/hpcloud/tail/Makefile
  vendor/github.com/hpcloud/tail/README.md
  vendor/github.com/hpcloud/tail/appveyor.yml
  vendor/github.com/hpcloud/tail/ratelimiter/Licence
  vendor/github.com/hpcloud/tail/ratelimiter/leakybucket.go
  vendor/github.com/hpcloud/tail/ratelimiter/memory.go
  vendor/github.com/hpcloud/tail/ratelimiter/storage.go
  vendor/github.com/hpcloud/tail/tail.go
  vendor/github.com/hpcloud/tail/tail_posix.go
  vendor/github.com/hpcloud/tail/tail_windows.go
  vendor/github.com/hpcloud/tail/util/util.go
  vendor/github.com/hpcloud/tail/watch/filechanges.go
  vendor/github.com/hpcloud/tail/watch/inotify.go
  vendor/github.com/hpcloud/tail/watch/inotify_tracker.go
  vendor/github.com/hpcloud/tail/watch/polling.go
  vendor/github.com/hpcloud/tail/watch/watch.go
  vendor/github.com/hpcloud/tail/winfile/winfile.go
  vendor/gopkg.in/fsnotify.v1/.editorconfig
  vendor/gopkg.in/fsnotify.v1/.gitignore
  vendor/gopkg.in/fsnotify.v1/.travis.yml
  vendor/gopkg.in/fsnotify.v1/AUTHORS
  vendor/gopkg.in/fsnotify.v1/CHANGELOG.md
  vendor/gopkg.in/fsnotify.v1/CONTRIBUTING.md
  vendor/gopkg.in/fsnotify.v1/LICENSE
  vendor/gopkg.in/fsnotify.v1/README.md
  vendor/gopkg.in/fsnotify.v1/fen.go
  vendor/gopkg.in/fsnotify.v1/fsnotify.go
  vendor/gopkg.in/fsnotify.v1/inotify.go
  vendor/gopkg.in/fsnotify.v1/inotify_poller.go
  vendor/gopkg.in/fsnotify.v1/kqueue.go
  vendor/gopkg.in/fsnotify.v1/open_mode_bsd.go
  vendor/gopkg.in/fsnotify.v1/open_mode_darwin.go
  vendor/gopkg.in/fsnotify.v1/windows.go
  vendor/gopkg.in/tomb.v1/LICENSE
  vendor/gopkg.in/tomb.v1/README.md
  vendor/gopkg.in/tomb.v1/tomb.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XXL

#486 Add logs to non root enabler
  cmd/security-profiles-operator/main.go
  internal/pkg/nonrootenabler/nonrootenabler.go
  internal/pkg/nonrootenabler/nonrootenabler_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#491 Retry log-enricher if container ID is empty
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/types.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#483 Add log-enricher e2e test
  hack/ci/e2e.sh
  test/e2e_test.go
  test/suite_test.go
  test/tc_log_enricher_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#492 Add seccomp audit metrics
  api/server/api.pb.go
  api/server/api.proto
  api/server/api_grpc.pb.go
  cmd/security-profiles-operator/main.go
  installation-usage.md
  internal/pkg/daemon/enricher/audit.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/types.go
  internal/pkg/daemon/metrics/metrics.go
  internal/pkg/daemon/server/server.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XL

#498 Add log enricher documentation
  installation-usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/L

#497 Reopen audit logs on rotation
  internal/pkg/daemon/enricher/enricher.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#496 Add metrics check for enricher e2e test
  test/suite_test.go
  test/tc_log_enricher_test.go
  test/tc_metrics_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#501 Switch to golang 1.16 for Vagrant
  .github/workflows/build.yml
  .github/workflows/test.yml
  dependencies.yaml
  hack/ci/Vagrantfile
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S

#502 Use native type for binding/recording kind
  api/profilebinding/v1alpha1/profilebinding_types.go
  api/profilerecording/v1alpha1/profilerecording_types.go
  internal/pkg/webhooks/binding/binding.go
  internal/pkg/webhooks/binding/binding_test.go
  internal/pkg/webhooks/recording/recording.go
  internal/pkg/webhooks/recording/recording_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#503 Allow syscall with ID 0
  internal/pkg/daemon/enricher/enricher.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#499 Make log enricher work with containerd
  installation-usage.md
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/types.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/M

#506 Add first enricher unit test
  cmd/security-profiles-operator/main.go
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/enricher/enricherfakes/fake_impl.go
  internal/pkg/daemon/enricher/impl.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XXL

#508 Make enricher types private
  internal/pkg/daemon/enricher/audit.go
  internal/pkg/daemon/enricher/audit_test.go
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/types.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#504 Fix golang 1.16 usage
  hack/ci/Vagrantfile
  hack/ci/env.sh
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S
