Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2021-02, with the labels that each got.

#245 Cleanup - .dockerignore files
  .dockerignore
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/S

#243 Feature - Speedup docker builds
  Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note, size/XS

#248 Fix-included the .git and version to .dockerignore
  .dockerignore
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#250 Clarify webhook installation instructions
  installation-usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#252 Fix intermittent issue with E2E tests
  Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#247 Add seccomp profile recording feature
  Makefile
  api/profilerecording/v1alpha1/groupversion_info.go
  api/profilerecording/v1alpha1/profilebinding_types.go
  api/profilerecording/v1alpha1/zz_generated.deepcopy.go
  cmd/security-profiles-operator/main.go
  deploy/base/rbac.yaml
  deploy/base/webhook/certificate.yaml
  deploy/base/webhook/config.yaml
  deploy/base/webhook/crd-binding.yaml
  deploy/base/webhook/crd-recording.yaml
  deploy/base/webhook/kustomization.yaml
  deploy/base/webhook/rbac.yaml
  deploy/base/webhook/service.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  deploy/webhook.yaml
  examples/profilerecording.yaml
  internal/pkg/config/config.go
  internal/pkg/controllers/profilerecorder/profilerecorder.go
  internal/pkg/controllers/spod/bindata/spod.go
  internal/pkg/webhooks/binding/webhook.go
  internal/pkg/webhooks/recording/webhook.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#256 Add profile recording 'kind' field
  api/profilerecording/v1alpha1/profilebinding_types.go
  cmd/security-profiles-operator/main.go
  deploy/base/webhook/crd-recording.yaml
  deploy/webhook.yaml
  examples/profilerecording.yaml
  internal/pkg/config/config.go
  internal/pkg/controllers/profilerecorder/profilerecorder.go
  internal/pkg/controllers/seccompprofile/seccompprofile.go
  internal/pkg/controllers/seccompprofile/seccompprofile_test.go
  internal/pkg/controllers/spod/bindata/spod.go
  internal/pkg/webhooks/binding/binding.go
  internal/pkg/webhooks/binding/binding_test.go
  internal/pkg/webhooks/recording/recording.go
  test/tc_default_profiles_test.go
  test/tc_delete_profiles_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, release-note-none, size/M

#255 Unify YAML syntax and fixup some comments
  api/profilebinding/v1alpha1/profilebinding_types.go
  deploy/base/config.yaml
  deploy/base/rbac.yaml
  deploy/base/webhook/certificate.yaml
  deploy/base/webhook/crd-binding.yaml
  deploy/base/webhook/rbac.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  deploy/webhook.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, release-note-none, size/L

#257 Add profile recording documentation
  installation-usage.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#259 Remove namespace from ClusterRoleBindings
  deploy/base/rbac.yaml
  deploy/base/webhook/rbac.yaml
  deploy/operator.yaml
  deploy/webhook.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#261 Revert fixes to dockerignore file
  .dockerignore
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#262 Remove nodeSelector from deployment and webhook
  deploy/base/operator.yaml
  deploy/base/webhook/deployment.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  deploy/webhook.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#263 Remove deploy/crd.yaml
  deploy/crd.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#264 Also listen to its own Namespace if RESTRICT_TO_NAMESPACE is given
  cmd/security-profiles-operator/main.go
Labels: approved, cncf-cla: yes, kind/bug, kind/flake, kind/regression, lgtm, release-note-none, size/S

#266 Use errors.Wrap instead of fmt.Errorf
  internal/pkg/controllers/spod/configmap_controller.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#260 Expand on seccomp example profiles
  examples/pod.yaml
  examples/profilebinding.yaml
  examples/seccompprofile.yaml
  installation-usage.md
  test/tc_default_profiles_test.go
  test/tc_profilebindings_test.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/L

#265 Reuse deployment image to daemon set
  cmd/security-profiles-operator/main.go
  deploy/base/kustomization.yaml
  deploy/base/operator.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  deploy/overlays/openshift-dev/kustomization.yaml
  internal/pkg/controllers/spod/configmap_controller.go
  internal/pkg/controllers/spod/setup.go
  internal/pkg/controllers/spod/setup_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/M

#268 Allow e2e test to receive custom image
  test/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#271 Fix e2e hello-world test image
  test/tc_base_profiles_test.go
  test/tc_profilebindings_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#269 Deploy default profiles via the manager
  Makefile
  deploy/profiles/base/kustomization.yaml
  deploy/profiles/base/nginx-1.19.1.yaml
  deploy/profiles/default-profiles.yaml
  deploy/profiles/namespace-default-profiles.yaml
  deploy/profiles/overlays/namespaced/kustomization.yaml
  deploy/profiles/overlays/namespaced/seccompprofile.yaml
  installation-usage.md
  internal/pkg/controllers/spod/bindata/default_profiles.go
  internal/pkg/controllers/spod/configmap_controller.go
  internal/pkg/controllers/spod/setup.go
  test/e2e_test.go
  test/tc_redeploy_operator_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XL

#273 Reuse manager imagePullPolicy for all other workloads
  deploy/base/config.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  internal/pkg/config/config.go
  internal/pkg/controllers/spod/configmap_controller.go
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#274 Print pod selector on wide profilerecording output
  api/profilerecording/v1alpha1/profilerecording_types.go
  deploy/base/webhook/crd-recording.yaml
  deploy/webhook.yaml
  internal/pkg/controllers/spod/setup.go
  profiles
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/S

#251 Add log enrichment feature for seccomp
  cmd/security-profiles-operator/main.go
  deploy/base/config.yaml
  deploy/base/kustomization.yaml
  deploy/base/operator.yaml
  deploy/base/rbac.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  internal/pkg/config/config.go
  internal/pkg/controllers/spod/bindata/spod.go
  internal/pkg/controllers/spod/configmap_controller.go
  internal/pkg/controllers/spod/setup.go
  internal/pkg/controllers/spod/setup_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#272 Add `SCMP_ARCH_NATIVE`
  api/seccompprofile/v1alpha1/seccompprofile_types.go
  deploy/base/crd.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XS

#277 Run as user nobody
  Dockerfile
  Dockerfile.ubi
  internal/pkg/controllers/spod/bindata/spod.go
  test/tc_default_profiles_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#281 Fix deployments for kustomize 3.9.3
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#278 Add personas and user story documents
  .github/ISSUE_TEMPLATE/feature.md
  README.md
  doc/personas.md
  doc/user-stories.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#283 Add basic Vagrant test job
  .github/workflows/e2e.yml
  .gitignore
  hack/ci/Vagrantfile
  hack/ci/env.sh
  hack/ci/install-cri-o.sh
  hack/ci/install-kubernetes.sh
  hack/ci/run.sh
Labels: approved, cncf-cla: yes, kind/design, lgtm, release-note-none, size/L

#284 e2e: Enable SELinux through an environment variable
  test/e2e_test.go
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#290 Make default nginx profile work with crun 0.17
  internal/pkg/controllers/spod/bindata/default_profiles.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#291 Add minimum profile example for crun
  examples/baseprofile-crun.yaml
  examples/baseprofile-runc.yaml
  installation-usage.md
  test/tc_base_profiles_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/M

#292 Make crun the default runtime for CRI-O tests
  hack/ci/install-cri-o.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#287 Add arm64 binary cross compilation support
  .gitignore
  Makefile
  nix/default-arm64.nix
  nix/default.nix
  nix/derivation.nix
  nix/nixpkgs.json
  nix/nixpkgs.nix
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/M

#294 Add crun to base profile e2e test
  hack/ci/install-cri-o.sh
  test/suite_test.go
  test/tc_base_profiles_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#295 Remove clusterRole and clusterRoleBinding overrides from namespaced-operator
  deploy/namespace-operator.yaml
  deploy/overlays/namespaced/clusterrole.yaml
  deploy/overlays/namespaced/clusterrolebinding.yaml
  deploy/overlays/namespaced/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#296 Add multi architecture image support
  Dockerfile
  Makefile
  README.md
  cloudbuild.yaml
  hack/image-cross.sh
  hack/pull-security-profiles-operator-build-image
  installation-usage.md
  nix/default-amd64.nix
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#298 Make kustomize a non requirement
  CONTRIBUTING.md
  Makefile
  hack/pull-security-profiles-operator-verify
  release.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#299 Record seccomp profiles already in `pending` state
  internal/pkg/controllers/profilerecorder/profilerecorder.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#300 Fix controller-gen `go` command within Makefile
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#301 Fix release.md image location for published images
  release.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#303 Add cachix GitHub action to speedup CI
  .github/workflows/build.yml
  Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#305 Use k8s.gcr.io debian-base image for container build
  Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#307 Rename `go-mod` target to `update-go-mod` and vendor
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#304 Move test related GitHub actions into one workflow
  .github/workflows/codeql-analysis.yml
  .github/workflows/e2e.yml
  .github/workflows/test.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#309 Pass pre-build operator image to e2e test
  .github/workflows/test.yml
  .gitignore
  Makefile
  hack/ci/Vagrantfile
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#310 Fix post-security-profiles-operator-push-image job
  Dockerfile
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#311 Stick to x86_64 nix binaries for image builds
  Dockerfile
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S

#312 Switch to go1.16 images for GitHub actions
  .github/workflows/build.yml
  .github/workflows/test.yml
  go.mod
  go.sum
  hack/pull-security-profiles-operator-build
  hack/pull-security-profiles-operator-test-unit
  hack/pull-security-profiles-operator-verify
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#297 Add profile recording e2e test
  .github/workflows/test.yml
  Makefile
  hack/ci/e2e.sh
  test/e2e_test.go
  test/suite_test.go
  test/tc_profilebindings_test.go
  test/tc_profilerecordings_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#314 Add profile recording `kubectl run` test
  test/e2e_test.go
  test/tc_profilerecordings_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#315 Add dedicated build image hosted on quay.io
  Dockerfile
  hack/build-image/Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#316 Add automatic build image push to quay.io
  .github/workflows/build.yml
  hack/build-image/Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S
