Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2021-03, with the labels that each got.

#332 e2e: Increase default wait timeout
  test/e2e_test.go
Labels: approved, cncf-cla: yes, kind/bug, kind/flake, kind/regression, lgtm, release-note-none, size/XS

#329 spod: Harden the selinuxd container
  internal/pkg/controllers/spod/bindata/spod.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/M

#325 Separate RBAC for daemon and deployment
  Makefile
  cmd/security-profiles-operator/main.go
  deploy/base/kustomization.yaml
  deploy/base/ns.yaml
  deploy/base/rbac.yaml
  deploy/base/role.yaml
  deploy/base/role_binding.yaml
  deploy/base/service_account.yaml
  deploy/base/webhook/deployment.yaml
  deploy/base/webhook/kustomization.yaml
  deploy/base/webhook/rbac.yaml
  deploy/base/webhook/role.yaml
  deploy/base/webhook/role_binding.yaml
  deploy/base/webhook/service_account.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  deploy/webhook.yaml
  internal/pkg/config/config.go
  internal/pkg/daemon/enricher/audit.go
  internal/pkg/daemon/enricher/audit_test.go
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/main.go
  internal/pkg/daemon/enricher/types.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/seccompprofile/seccompprofile_test.go
  internal/pkg/daemon/selinuxpolicy/selinuxpolicy_controller.go
  internal/pkg/daemon/selinuxpolicy/setup.go
  internal/pkg/daemon/selinuxpolicy/utils.go
  internal/pkg/manager/spod/bindata/default_profiles.go
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/configmap_controller.go
  internal/pkg/manager/spod/setup.go
  internal/pkg/manager/spod/setup_test.go
  internal/pkg/webhooks/binding/binding.go
  internal/pkg/webhooks/recording/recording.go
  test/tc_default_profiles_test.go
  test/tc_delete_profiles_test.go
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, release-note, size/XXL

#334 Verify generated code on deployment generation
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#340 Add auto generate profiles use case
  doc/user-stories.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#339 Log enricher running unprivileged and extends supported audit line types
  go.mod
  go.sum
  internal/pkg/daemon/enricher/audit.go
  internal/pkg/daemon/enricher/audit_test.go
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/container_test.go
  internal/pkg/daemon/enricher/main.go
  internal/pkg/manager/spod/bindata/spod.go
  vendor/github.com/cirocosta/dmesg_exporter/LICENSE
  vendor/github.com/cirocosta/dmesg_exporter/kmsg/kmsg.go
  vendor/github.com/cirocosta/dmesg_exporter/reader/reader.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XL

#338 Add leases RBAC to webhook
  deploy/base/webhook/role.yaml
  deploy/webhook.yaml
  internal/pkg/webhooks/binding/binding.go
  internal/pkg/webhooks/recording/recording.go
Labels: approved, cncf-cla: yes, kind/regression, lgtm, release-note-none, size/M

#335 Switch to latest CRI-O master for e2e tests
  hack/ci/install-cri-o.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#345 Restore the default tolerations
  deploy/base/config.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/M

#344 Add multi-container recording support
  installation-usage.md
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/webhooks/recording/recording.go
  test/e2e_test.go
  test/tc_profilerecordings_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/L

#346 Re-enable SELinux by default on OCP
  Makefile
  deploy/overlays/openshift-dev/enable-selinux.yaml
  deploy/overlays/openshift-dev/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#348 spod: Lower the selinuxd CPU requests and limits
  internal/pkg/manager/spod/bindata/spod.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#342 Handle Updates of SPOD object
  api/spod/v1alpha1/spod_types.go
  deploy/base/role.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  internal/pkg/manager/spod/spod_controller.go
  test/e2e_test.go
  test/suite_test.go
  test/tc_spod_update_selinux_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, release-note, size/L

#350 Remove targetWorkload field from seccomp profiles
  api/seccompprofile/v1alpha1/seccompprofile_types.go
  deploy/base/crd.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  examples/baseprofile-crun.yaml
  examples/baseprofile-runc.yaml
  examples/pod.yaml
  examples/seccompprofile.yaml
  installation-usage.md
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/seccompprofile/seccompprofile_test.go
  internal/pkg/manager/spod/bindata/default_profiles.go
  test/tc_base_profiles_test.go
  test/tc_default_profiles_test.go
  test/tc_delete_profiles_test.go
  test/tc_profilebindings_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/L

#352 Add status badges for GitHub actions
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#351 Add use case about correlating log entries to containers
  doc/user-stories.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#354 Fix error message if SPOD API scheme registration fails
  cmd/security-profiles-operator/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#359 Fix deployment config CRD race
  cmd/security-profiles-operator/main.go
  deploy/base/config.yaml
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/L

#362 Automatically retry VM provisioning
  Makefile
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#366 Give baseprofile tests time for reconciliation
  test/tc_base_profiles_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S

#356 Add jhrozek to reviewers
  OWNERS
Labels: approved, cncf-cla: yes, kind/feature, release-note-none, size/XS

#368 tests: Enable SELinux in tests
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, release-note-none, size/S

#370 Do not throw "Profile saved on disk" event if profile not modified
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/seccompprofile/seccompprofile_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#371 Update golangci-lint to v1.38.0
  .golangci.yml
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#364 Use sync.Map for pods to watch
  internal/pkg/daemon/profilerecorder/profilerecorder.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#374 Refactor webhook utils and add tests
  internal/pkg/webhooks/binding/binding.go
  internal/pkg/webhooks/binding/binding_test.go
  internal/pkg/webhooks/recording/recording.go
  internal/pkg/webhooks/utils/utils.go
  internal/pkg/webhooks/utils/utils_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#380 Add unit test infrastructure for recording webhook
  internal/pkg/webhooks/recording/impl.go
  internal/pkg/webhooks/recording/recording.go
  internal/pkg/webhooks/recording/recording_test.go
  internal/pkg/webhooks/recording/recordingfakes/fake_impl.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XL

#372 Add selinuxd's selinux profile
  deploy/base/kustomization.yaml
  deploy/base/profiles/selinuxd.cil
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/spod_controller.go
  internal/pkg/nonrootenabler/nonrootenabler.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/L

#378 Add `release-note-none` label to dependabot updates
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#388 Do not include YEAR in generated boilerplate
  Makefile
  hack/boilerplate/boilerplate.generatego.txt
  internal/pkg/nonrootenabler/nonrootenablerfakes/fake_impl.go
  internal/pkg/webhooks/recording/recordingfakes/fake_impl.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M
