Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2021-01, with the labels that each got.

#180 Change controller manager to be a Deployment
  cmd/security-profiles-operator/main.go
  deploy/base/config.yaml
  deploy/base/kustomization.yaml
  deploy/base/operator.yaml
  deploy/base/rbac.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  deploy/overlays/namespaced/deployment.yaml
  deploy/overlays/namespaced/kustomization.yaml
  examples/config.yaml
  internal/pkg/config/config.go
  internal/pkg/controllers/selinuxpolicy/configmap_controller.go
  internal/pkg/controllers/selinuxpolicy/selinuxpolicy_controller.go
  internal/pkg/controllers/selinuxpolicy/setup.go
  internal/pkg/controllers/selinuxpolicy/utils.go
  internal/pkg/controllers/spod/bindata/bindata.go
  internal/pkg/controllers/spod/bindata/spod.go
  internal/pkg/controllers/spod/configmap_controller.go
  internal/pkg/controllers/spod/setup.go
  internal/pkg/controllers/spod/setup_test.go
  test/e2e_test.go
  test/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XXL

#181 Add ability to set GOFLAGS from Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#184 Add Makefile targets for easy development in OpenShift
  Makefile
  deploy/overlays/openshift-dev/kustomization.yaml
  deploy/overlays/openshift-dev/operator-profile.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#187 feature - Included settings for dependabot
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#183 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/M

#196 Add toleration for control-plane taint
  deploy/base/operator.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  internal/pkg/controllers/selinuxpolicy/configmap_controller.go
  internal/pkg/controllers/spod/bindata/spod.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S

#197 Pre-req for common upgrade
  Dockerfile
  Makefile
  hack/pull-security-profiles-operator-build
  hack/pull-security-profiles-operator-test-unit
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/S

#203 Fix UBI Dockerfile
  Dockerfile.ubi
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#208 Fix a copy-paste error when setting DaemonTunables
  cmd/security-profiles-operator/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#209 Add GoLand private dir to gitignore
  .gitignore
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#204 Add myself to reviewers in OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#206 Use typed bindata for DaemonSet
  api/seccompprofile/v1alpha1/seccompprofile_types.go
  api/seccompprofile/v1alpha1/zz_generated.deepcopy.go
  api/selinuxpolicy/v1alpha1/zz_generated.deepcopy.go
  internal/pkg/controllers/spod/bindata/bindata.go
  internal/pkg/controllers/spod/bindata/spod.go
  internal/pkg/controllers/spod/setup.go
  internal/pkg/controllers/spod/setup_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#207 Update kind node image to v1.20.0
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#202 Re-add runtime/default seccomp profile to operator deployment
  deploy/base/operator.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#215 Add libseccomp-static to fix container image build
  Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#185 fix - builds for darwin
  .github/workflows/build.yml
  Makefile
  go.mod
  go.sum
  internal/pkg/controllers/profile/profile.go
  internal/pkg/controllers/profile/profile_test.go
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/L

#216 Updated instructions for contributions.
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/M

#179 Add ProfileBinding CRD and webhook
  Makefile
  api/profilebinding/v1alpha1/groupversion_info.go
  api/profilebinding/v1alpha1/profilebinding_types.go
  api/profilebinding/v1alpha1/zz_generated.deepcopy.go
  cmd/security-profiles-operator/main.go
  deploy/base/certificate.yaml
  deploy/base/crd.yaml
  deploy/base/kustomization.yaml
  deploy/base/operator.yaml
  deploy/base/profiles/security-profiles-operator.json
  deploy/base/rbac.yaml
  deploy/base/service.yaml
  deploy/base/webhookconfig.yaml
  deploy/namespace-operator.yaml
  deploy/operator.yaml
  examples/profilebinding.yaml
  installation-usage.md
  internal/pkg/webhooks/binding/webhook.go
  internal/pkg/webhooks/binding/webhook_test.go
  test/e2e_test.go
  test/suite_test.go
  test/tc_profilebindings_test.go
Labels: approved, cncf-cla: yes, kind/api-change, kind/feature, lgtm, release-note, size/XXL

#219 Update golangci-lint and run tests in parallel
  .golangci.yml
  Makefile
  hack/pull-security-profiles-operator-verify
  internal/pkg/controllers/profile/profile_test.go
  internal/pkg/controllers/spod/setup_test.go
  internal/pkg/version/version_test.go
  internal/pkg/webhooks/binding/webhook_test.go
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#226 Log cluster state before tearing down e2e test
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/bug, kind/flake, lgtm, release-note-none, size/XS

#230 Bump kind to v0.10.0
  test/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#233 make: Deploy cert-manager before deploying the operator in OpenShift
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#234 make: Set EnableSelinux=true through kustomize for OpenShift
  deploy/overlays/openshift-dev/enable-selinux.yaml
  deploy/overlays/openshift-dev/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#229 Feature - included question for tests in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#217 codecov for tracking codecoverage tracking
  .codecov.yml
  .github/workflows/build.yml
  .github/workflows/test.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#236 Fix - fixed the golanglintci issues for macos
  .github/workflows/build.yml
  .golangci.yml
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/S

#239 selinux: Wait for the /ready endpoint before writing the policies, write policies only if they differ
  internal/pkg/controllers/selinuxpolicy/selinuxpolicy_controller.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/M

#240 Add wait condition for webhook cert
  test/suite_test.go
  test/tc_profilebindings_test.go
Labels: approved, cncf-cla: yes, kind/flake, lgtm, release-note-none, size/S
