Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2022-12, with the labels that each got.

#1343 profilerecorder: Don't issue seccomp events for recording of any profile
  internal/pkg/daemon/profilerecorder/profilerecorder.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1351 Add `verify-format` target to reformat proto and c files
  .clang-format
  Makefile
  api/grpc/bpfrecorder/api.proto
  api/grpc/enricher/api.proto
  api/grpc/metrics/api.proto
  dependencies.yaml
  hack/pull-security-profiles-operator-verify
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.c
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#1354 Bump nix to v2.12.0 and nixpkgs
  Dockerfile.build-image
  dependencies.yaml
  nix/nixpkgs.json
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1355 Dockerfile.ubi: bump images, remove workaround
  Dockerfile.ubi
  dependencies.yaml
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1347 OLM: Add separators between CR examples to make sure all CRDs have an example in the bundle
  Makefile
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/separator.yaml
  examples/rawselinuxprofile.yaml
  examples/selinuxprofile.yaml
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#1353 Parse ebpf event in one step
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.c
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/bpfrecorder/generated.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M
