Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2022-10, with the labels that each got.

#1196 Use an existing constant instead of redefining our own
  internal/pkg/nodestatus/nodestatus.go
  internal/pkg/util/names.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1202 docs: add a note to respect control-plane label on an AKS cluster
  installation-usage.md
Labels: cncf-cla: yes, size/S, ok-to-test, lgtm, release-note-none, approved, kind/documentation

#1201 Add SECCOMP_FILTER_FLAG_WAIT_KILLABLE_RECV
  api/seccompprofile/v1beta1/seccompprofile_types.go
  bundle/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
  deploy/base-crds/crd.yaml
  deploy/base-crds/crds/seccompprofile.yaml
  deploy/helm/crds/crds.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
Labels: kind/feature, release-note, cncf-cla: yes, kind/api-change, size/S, ok-to-test, lgtm, approved

#1205 Switch to libbpf_1 dependency in nix
  nix/derivation-bpf.nix
  nix/derivation.nix
  nix/nixpkgs.json
  nix/overlay.nix
Labels: release-note, cncf-cla: yes, size/S, lgtm, approved, kind/cleanup

#1211 doc: Document how to restrict OLM installs to a single namespace
  installation-usage.md
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/documentation

#1219 Add KubeCon EU 2022 talk
  installation-usage.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/documentation

#1232 spod: Make the webhook's ObjectSelector configurable
  api/spod/v1alpha1/spod_types.go
  api/spod/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
  deploy/base-crds/crds/securityprofilesoperatordaemon.yaml
  deploy/helm/crds/crds.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  installation-usage.md
  internal/pkg/manager/spod/bindata/webhook.go
  test/tc_webhook_config_test.go
Labels: kind/feature, size/L, release-note, cncf-cla: yes, kind/api-change, lgtm, approved

#1235 config: Allow enabling the log enricher on install time using the `ENABLE_LOG_ENRICHER` variable
  installation-usage.md
  internal/pkg/config/config.go
  internal/pkg/manager/spod/spod_controller.go
Labels: kind/feature, release-note, cncf-cla: yes, size/S, lgtm, approved

#1237 Bump to v0.5.0
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  installation-usage.md
  release.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation, size/M

#1243 Bump back to dev
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  installation-usage.md
  release.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation, size/M

#1252 Use directly the box url instead of the metadata when downloading the vagrant box for flatcar linux
  hack/ci/Vagrantfile-flatcar
Labels: release-note, cncf-cla: yes, needs-ok-to-test, lgtm, approved, size/XS

#1253 Upgrade golang.org/x/text to get around CVE warnings
  go.mod
  go.sum
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1257 recordingmerger: Fix producing union of SELinux permissions
  internal/pkg/manager/recordingmerger/merge_utils.go
  internal/pkg/manager/recordingmerger/merge_utils_test.go
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, release-note-none, approved

#1236 handle node deletion
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/role.yaml
  deploy/helm/templates/static-resources.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  deploy/overlays/webhook/role.yaml
  deploy/webhook-operator.yaml
  internal/pkg/manager/nodestatus/nodestatus.go
  internal/pkg/nodestatus/nodestatus.go
  internal/pkg/util/finalizers.go
  test/tc_delete_profiles_test.go
Labels: kind/bug, size/L, release-note, cncf-cla: yes, ok-to-test, lgtm, approved

#1251 Propose ccojocar and Vincent056 as reviewers
  OWNERS
Labels: cncf-cla: yes, release-note-none, approved, size/XS, kind/documentation
