Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2022-03, with the labels that each got.

#821 Update libbpf to v0.7.0
  bpf-support.md
  dependencies.yaml
  go.mod
  go.sum
  hack/install-libbpf.sh
  internal/pkg/daemon/bpfrecorder/btf/centos/7/x86_64/3.10.0-1160.59.1.el7.x86_64.btf
  internal/pkg/daemon/bpfrecorder/generated.go
  internal/pkg/version/version_bpf_supported.go
  nix/nixpkgs.json
  vendor/github.com/aquasecurity/libbpfgo/.gitignore
  vendor/github.com/aquasecurity/libbpfgo/helpers/argumentParsers.go
  vendor/github.com/aquasecurity/libbpfgo/helpers/elf.go
  vendor/github.com/aquasecurity/libbpfgo/helpers/kernel_symbols.go
  vendor/github.com/aquasecurity/libbpfgo/libbpfgo.go
  vendor/modules.txt
Labels: size/XXL, release-note, cncf-cla: yes, lgtm, approved, kind/cleanup

#819 Bump test Kubernetes to v1.23.4
  dependencies.yaml
  hack/ci/Vagrantfile-fedora
  hack/ci/Vagrantfile-ubuntu
  hack/ci/install-kubernetes.sh
  test/suite_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#822 Update kind to v0.12.0
  dependencies.yaml
  test/suite_test.go
Labels: cncf-cla: yes, size/S, release-note-none, approved, kind/cleanup

#832 fix: get the makefile deployments target working on darwin
  Makefile
Labels: cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, size/XS

#829 Bump CRI-O CI version and update script
  dependencies.yaml
  hack/ci/Vagrantfile-ubuntu
  hack/ci/install-cri-o.sh
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#830 fix: health probe of seccomp controller should be ready if a node supports seccomp
  internal/pkg/daemon/seccompprofile/seccompprofile.go
Labels: cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, size/M

#840 test: make the e2e tsts to run on macos
  test/e2e_test.go
  test/tc_run_pod_test.go
Labels: release-note, cncf-cla: yes, ok-to-test, lgtm, approved, size/M

#847 Bump Kubernetes to v1.23.5 and CRI-O to v1.23.2
  dependencies.yaml
  hack/ci/Vagrantfile-ubuntu
  hack/ci/install-cri-o.sh
  hack/ci/install-kubernetes.sh
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#852 Update gocritic config
  .golangci.yml
  api/apparmorprofile/v1alpha1/apparmorprofile_types.go
  api/profilebinding/v1alpha1/profilebinding_types.go
  api/profilerecording/v1alpha1/profilerecording_types.go
  api/seccompprofile/v1beta1/seccompprofile_types.go
  api/secprofnodestatus/v1alpha1/secprofnodestatus_types.go
  api/selinuxprofile/v1alpha2/rawselinuxprofile_types.go
  api/selinuxprofile/v1alpha2/selinuxprofile_types.go
  api/spod/v1alpha1/spod_types.go
  cmd/security-profiles-operator/main.go
  internal/pkg/daemon/apparmorprofile/apparmor_supported.go
  internal/pkg/daemon/apparmorprofile/apparmorprofile.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/bpfrecorder/generate/main.go
  internal/pkg/daemon/bpfrecorder/impl.go
  internal/pkg/daemon/enricher/audit_test.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/profilerecorder/impl.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/profilerecorder/profilerecorder_test.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/seccompprofile/seccompprofile_test.go
  internal/pkg/daemon/selinuxprofile/common_controller.go
  internal/pkg/daemon/selinuxprofile/rawselinuxprofile.go
  internal/pkg/daemon/selinuxprofile/selinuxprofile.go
  internal/pkg/daemon/selinuxprofile/selinuxprofile_test.go
  internal/pkg/manager/nodestatus/nodestatus.go
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/spod_controller.go
  internal/pkg/util/names.go
  internal/pkg/webhooks/binding/binding.go
  internal/pkg/webhooks/binding/binding_test.go
  internal/pkg/webhooks/binding/impl.go
  internal/pkg/webhooks/recording/impl.go
  internal/pkg/webhooks/recording/recording.go
  test/e2e_test.go
  test/suite_test.go
  test/tc_base_profiles_test.go
  test/tc_bpf_recorder_test.go
  test/tc_delete_profiles_test.go
  test/tc_profilebindings_test.go
  test/tc_profilerecordings_test.go
  test/tc_selinux_base_usage_test.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#855 Fix and verify mocks in CI
  Makefile
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#856 Enable revive and gomoddirectives linters
  .golangci.yml
  internal/pkg/atomic/bool.go
  internal/pkg/daemon/enricher/audit.go
  internal/pkg/daemon/enricher/audit_test.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/enricher/types.go
  internal/pkg/daemon/profilerecorder/impl.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/profilerecorder/profilerecorderfakes/fake_impl.go
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/spod_controller.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#859 Use go 1.18 buildinfo for version output
  Makefile
  cmd/security-profiles-operator/main.go
  internal/pkg/version/version.go
  internal/pkg/version/version_test.go
Labels: kind/feature, size/L, release-note, cncf-cla: yes, lgtm, approved

#863 Update cert-manager to v1.7.2
  dependencies.yaml
  installation-usage.md
  test/e2e_test.go
Labels: release-note, cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup

#864 Use reflection for version field output
  internal/pkg/version/version.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#860 Make version.Get fallible
  cmd/security-profiles-operator/main.go
  internal/pkg/version/version.go
  internal/pkg/version/version_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#865 Bump kustomize to v4.5.3
  Makefile
  dependencies.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#868 Update kustomize to v4.5.4
  Makefile
  dependencies.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#870 Fix check that verifies if catalog logs are empty
  hack/ci/e2e-olm.sh
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#871 tests: Run the OLM tests with debug mode on
  hack/ci/e2e-olm.sh
Labels: cncf-cla: yes, kind/flake, lgtm, release-note-none, approved, size/XS, kind/cleanup

#869 Add read-only rootfs to metrics container
  internal/pkg/manager/spod/bindata/spod.go
Labels: kind/feature, release-note, cncf-cla: yes, lgtm, approved, size/XS

#872 Automatically push catalog and bundle
  .github/workflows/olm_tests.yaml
  .gitignore
  bundle.Dockerfile
  bundle/manifests/metrics-token_v1_secret.yaml
  bundle/manifests/security-profiles-operator-profile_v1_configmap.yaml
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_apparmorprofiles.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_profilebindings.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_profilerecordings.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_securityprofilenodestatuses.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
  bundle/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/spo-metrics-client_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/spo-webhook_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/spo-webhook_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/spo-webhook_v1_serviceaccount.yaml
  bundle/manifests/spod_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/spod_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/spod_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/spod_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/spod_v1_serviceaccount.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  hack/ci/e2e-olm.sh
  hack/image-cross.sh
Labels: kind/feature, size/XXL, cncf-cla: yes, lgtm, release-note-none, approved

#876 Manually install `opm` on image build
  dependencies.yaml
  hack/image-cross.sh
Labels: cncf-cla: yes, kind/failing-test, size/S, lgtm, release-note-none, approved
