Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2022-08, with the labels that each got.

#1060 make: remove the hack script
  Makefile
  bundle/manifests/security-profiles-operator-profile_v1_configmap.yaml
  hack/extract-cm.py
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#1067 helm: Package and save chart in a GitHub release.
  .github/workflows/helm-chart-package.yaml
Labels: cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, kind/cleanup, size/M

#1071 e2e: Add a breakpoint func
  test/suite_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1083 nodestatus: Only log low-level messages if verbosity is increased
  internal/pkg/manager/nodestatus/nodestatus.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1082 nodestatus: Remove dead code
  internal/pkg/manager/nodestatus/nodestatus.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1089 Bump tags for UBI-based Dockerfile
  Dockerfile.ubi
Labels: kind/bug, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#1088 Roll back problematic pod labeling feature
  api/spod/v1alpha1/spod_types.go
  bundle/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
  bundle/manifests/spod_rbac.authorization.k8s.io_v1_clusterrole.yaml
  cmd/security-profiles-operator/main.go
  deploy/base-crds/crds/securityprofilesoperatordaemon.yaml
  deploy/base/role.yaml
  deploy/helm/crds/crds.yaml
  deploy/helm/templates/static-resources.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/enricher/enricherfakes/fake_impl.go
  internal/pkg/daemon/enricher/impl.go
  internal/pkg/manager/spod/spod_controller.go
  test/e2e_test.go
  test/suite_test.go
  test/tc_selinux_label_problematic_test.go
Labels: kind/feature, size/L, release-note, cncf-cla: yes, lgtm, approved, kind/cleanup

#1096 Fix calico link
  hack/ci/Vagrantfile-flatcar
Labels: kind/bug, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1097 deploy: Set the NS for spod SA explicitly to allow privileged pods under OCP 4.12+
  bundle/manifests/spod_rbac.authorization.k8s.io_v1_rolebinding.yaml
  deploy/base/role_binding.yaml
  deploy/helm/templates/static-resources.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#1102 build: Fix flaky command for flat car
  .github/workflows/test.yml
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1105 Fix tag usage and image loading in image builds
  .github/workflows/build.yml
Labels: kind/bug, cncf-cla: yes, kind/regression, size/S, lgtm, release-note-none, approved

#1072 Bump golangci-lint to v1.48.0
  .golangci.yml
  Makefile
  api/apparmorprofile/v1alpha1/apparmorprofile_types.go
  api/apparmorprofile/v1alpha1/groupversion_info.go
  api/profilebinding/v1alpha1/profilebinding_types.go
  api/profilerecording/v1alpha1/profilerecording_types.go
  api/seccompprofile/v1beta1/seccompprofile_types.go
  api/secprofnodestatus/v1alpha1/secprofnodestatus_types.go
  api/selinuxprofile/v1alpha2/rawselinuxprofile_types.go
  api/selinuxprofile/v1alpha2/selinuxprofile_types.go
  api/spod/v1alpha1/spod_types.go
  cmd/security-profiles-operator/main.go
  dependencies.yaml
  internal/pkg/daemon/apparmorprofile/apparmor_supported.go
  internal/pkg/daemon/apparmorprofile/apparmorprofile.go
  internal/pkg/daemon/bpfrecorder/generate/main.go
  internal/pkg/daemon/enricher/audit_test.go
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/profilerecorder/profilerecorder_test.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/selinuxprofile/common_controller.go
  internal/pkg/daemon/selinuxprofile/rawselinuxprofile.go
  internal/pkg/daemon/selinuxprofile/selinuxprofile_test.go
  internal/pkg/manager/nodestatus/nodestatus.go
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/setup_test.go
  internal/pkg/manager/spod/spod_controller.go
  internal/pkg/util/names.go
  internal/pkg/version/version.go
  internal/pkg/webhooks/binding/binding.go
  internal/pkg/webhooks/binding/binding_test.go
  internal/pkg/webhooks/binding/impl.go
  internal/pkg/webhooks/recording/impl.go
  internal/pkg/webhooks/recording/recording.go
  test/suite_test.go
  test/tc_delete_profiles_test.go
  test/tc_selinux_base_usage_test.go
  test/tc_webhook_config_test.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#1107 Fix container repository for SPO container build
  .github/workflows/build.yml
Labels: kind/bug, cncf-cla: yes, kind/regression, lgtm, release-note-none, approved, size/XS

#1113 version: Verify the helm chart's versions.
  dependencies.yaml
  deploy/helm/Chart.yaml
Labels: cncf-cla: yes, needs-ok-to-test, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1109 Switch to go 1.19
  .github/workflows/build.yml
  .github/workflows/olm_tests.yaml
  .github/workflows/test.yml
  dependencies.yaml
  go.mod
  hack/ci/Vagrantfile-fedora
  hack/ci/Vagrantfile-flatcar
  hack/ci/Vagrantfile-ubuntu
  nix/derivation-bpf.nix
  nix/derivation.nix
  nix/nixpkgs.json
Labels: release-note, cncf-cla: yes, lgtm, approved, kind/cleanup, size/M

#1115 Move hasheddan and cmurphy to emeritus state
  OWNERS
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1110 Process bpf events in parallel
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
Labels: kind/feature, size/L, release-note, cncf-cla: yes, lgtm, approved

#1121 Fix flatcar e2e test
  Makefile
  hack/ci/Vagrantfile-flatcar
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#1116 Bump golangci-lint to v1.49.0
  .golangci.yml
  Makefile
  cmd/security-profiles-operator/main.go
  dependencies.yaml
  internal/pkg/daemon/metrics/impl.go
  internal/pkg/util/constants.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1123 Update GitHub runners to use ubuntu 22.04
  .github/workflows/build.yml
  .github/workflows/olm_tests.yaml
  .github/workflows/test.yml
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1125 workflows: Set the E2E_TEST_FLAKY_TESTS_ONLY=true variable inside the test VM
  .github/workflows/test.yml
Labels: kind/bug, cncf-cla: yes, kind/failing-test, size/S, lgtm, release-note-none, approved

#1126 Remove unused env variable
  hack/ci/e2e-fedora.sh
  hack/ci/e2e-static-webhook.sh
  hacking.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1128 Update CRI-O to v1.25.0 and cosign
  dependencies.yaml
  hack/ci/install-cri-o.sh
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1129 Use clang 14 for building the ebpf module
  dependencies.yaml
  internal/pkg/daemon/bpfrecorder/btf/amzn/2/arm64/4.14.290-217.505.amzn2.aarch64.btf
  internal/pkg/daemon/bpfrecorder/btf/amzn/2/x86_64/4.14.290-217.505.amzn2.x86_64.btf
  internal/pkg/daemon/bpfrecorder/btf/centos/7/x86_64/3.10.0-1160.76.1.el7.x86_64.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/arm64/4.15.0-1139-aws.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/arm64/4.15.0-189-generic.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/arm64/4.15.0-191-generic.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/x86_64/4.15.0-1131-gcp.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/x86_64/4.15.0-1134-gcp.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/x86_64/4.15.0-1139-aws.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/x86_64/4.15.0-1149-azure.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/x86_64/4.15.0-191-generic.btf
  internal/pkg/daemon/bpfrecorder/generated.go
  nix/derivation-bpf.nix
Labels: size/XXL, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup
