Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2022-05, with the labels that each got.

#918 hacking.md: Document E2E_TEST_LABEL_POD_DENIALS
  hacking.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/documentation

#917 spod: Provide explicit selector to the servicemonitor
  internal/pkg/manager/spod/bindata/servicemonitor.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#924 e2e: Don't deploy cert-manager on OCP
  test/e2e_test.go
  test/suite_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#916 metrics: Add SELinux related audit metrics to the enricher
  api/grpc/metrics/api.pb.go
  api/grpc/metrics/api.proto
  api/grpc/metrics/api_grpc.pb.go
  installation-usage.md
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/metrics/grpc.go
  internal/pkg/daemon/metrics/metrics.go
Labels: kind/feature, size/L, release-note, cncf-cla: yes, lgtm, approved

#931 Bump Kubernetes and CRI-O to v1.24.0
  dependencies.yaml
  hack/ci/Vagrantfile-ubuntu
  hack/ci/install-cri-o.sh
  hack/ci/install-kubernetes.sh
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#935 Avoid using context.Background
  internal/pkg/daemon/profilerecorder/impl.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/profilerecorder/profilerecorder_test.go
  internal/pkg/daemon/profilerecorder/profilerecorderfakes/fake_impl.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#937 Pin crossplane-runtime to the latest release
  go.mod
  go.sum
  vendor/github.com/crossplane/crossplane-runtime/apis/common/v1/connection_details.go
  vendor/github.com/crossplane/crossplane-runtime/apis/common/v1/merge.go
  vendor/github.com/crossplane/crossplane-runtime/apis/common/v1/policies.go
  vendor/github.com/crossplane/crossplane-runtime/apis/common/v1/resource.go
  vendor/github.com/crossplane/crossplane-runtime/apis/common/v1/zz_generated.deepcopy.go
  vendor/github.com/crossplane/crossplane-runtime/pkg/errors/errors.go
  vendor/github.com/crossplane/crossplane-runtime/pkg/meta/meta.go
  vendor/github.com/crossplane/crossplane-runtime/pkg/resource/api.go
  vendor/github.com/crossplane/crossplane-runtime/pkg/resource/interfaces.go
  vendor/github.com/crossplane/crossplane-runtime/pkg/resource/providerconfig.go
  vendor/github.com/crossplane/crossplane-runtime/pkg/resource/resource.go
  vendor/github.com/crossplane/crossplane-runtime/pkg/test/cmp.go
  vendor/github.com/crossplane/crossplane-runtime/pkg/test/fake.go
  vendor/github.com/spf13/afero/README.md
  vendor/github.com/spf13/afero/cacheOnReadFs.go
  vendor/github.com/spf13/afero/unionFile.go
  vendor/modules.txt
Labels: size/XXL, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#914 Bump nixpkgs (and update golang to v1.18.2)
  Dockerfile.build-image
  bundle/manifests/security-profiles-operator-profile_v1_configmap.yaml
  dependencies.yaml
  deploy/base/profiles/security-profiles-operator.json
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  nix/nixpkgs.json
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#942 Remove configmap RBAC from manager
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/role.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  internal/pkg/manager/spod/spod_controller.go
Labels: release-note, cncf-cla: yes, lgtm, approved, kind/cleanup, size/M

#944 deploy: Annotate the NS to allow running privileged
  deploy/base/ns.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
Labels: kind/bug, release-note, cncf-cla: yes, size/S, lgtm, approved

#947 Trim spod RBAC
  bundle/manifests/spod_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/spod_rbac.authorization.k8s.io_v1_role.yaml
  deploy/base/role.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  internal/pkg/daemon/apparmorprofile/apparmorprofile.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/selinuxprofile/common_controller.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#949 Automatically update github actions
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#938 Print serviceaccount RBAC after e2e fedora run
  .github/workflows/test.yml
  dependencies.yaml
  hack/ci/Vagrantfile-fedora
  hack/ci/install-audit2rbac.sh
  hack/ci/print-rbac.sh
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation, size/M

#960 Remove version comments in GitHub actions
  .github/workflows/build.yml
  .github/workflows/olm_tests.yaml
  .github/workflows/test.yml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#943 Improve webhook RBAC
  bundle/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/spo-webhook_rbac.authorization.k8s.io_v1_role.yaml
  deploy/base/role.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  internal/pkg/webhooks/binding/binding.go
  internal/pkg/webhooks/recording/recording.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#940 Bump kind to v0.14.0
  dependencies.yaml
  test/suite_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#967 Improve build flags and targets
  Makefile
  api/grpc/bpfrecorder/api.pb.go
  api/grpc/bpfrecorder/api_grpc.pb.go
  api/grpc/enricher/api.pb.go
  api/grpc/enricher/api_grpc.pb.go
  api/grpc/metrics/api.pb.go
  api/grpc/metrics/api_grpc.pb.go
  go.mod
  go.sum
  internal/pkg/tools/tools.go
  vendor/github.com/mogensen/kubernetes-split-yaml/.gitattributes
  vendor/github.com/mogensen/kubernetes-split-yaml/.gitignore
  vendor/github.com/mogensen/kubernetes-split-yaml/Readme.md
  vendor/github.com/mogensen/kubernetes-split-yaml/kubernetes-resources.go
  vendor/github.com/mogensen/kubernetes-split-yaml/main.go
  vendor/github.com/mogensen/kubernetes-split-yaml/model.go
  vendor/github.com/mogensen/kubernetes-split-yaml/newline_darwin.go
  vendor/github.com/mogensen/kubernetes-split-yaml/newline_linux.go
  vendor/github.com/mogensen/kubernetes-split-yaml/newline_windows.go
  vendor/github.com/mogensen/kubernetes-split-yaml/yaml.go
  vendor/modules.txt
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup
