Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2022-09, with the labels that each got.

#1137 Bump ubi-minimal
  Dockerfile.ubi
Labels: cncf-cla: yes, kind/flake, lgtm, release-note-none, approved, size/XS

#1131 fix bpf-recorder syscall map out of capacity
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.c
  internal/pkg/daemon/bpfrecorder/generated.go
Labels: kind/bug, cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, size/XS

#1139 Update libbpf to v1.0.0
  dependencies.yaml
  hack/install-libbpf.sh
Labels: release-note, cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup

#1138 Configure Dependabot to also update docker tags
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1145 Update docs how to use OperatorHub.io on OpenShift
  doc/img/openshift-install.png
  installation-usage.md
Labels: release-note, cncf-cla: yes, lgtm, approved, kind/documentation, size/M

#1146 Add OperatorHub category and release docs
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/clusterserviceversion.yaml
  release.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/documentation

#1148 Enable OpenShift cluster monitoring for namespace
  deploy/base/ns.yaml
  deploy/helm/templates/static-resources.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  examples/olm/operatorhub-io.yaml
Labels: kind/bug, release-note, cncf-cla: yes, size/S, lgtm, approved

#1151 Fix olm CI tests
  examples/olm/install-resources.yaml
  examples/olm/operatorhub-io.yaml
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#1153 tests: Run the flaky tests, too
  Makefile
  test/e2e_flaky_test.go
  test/e2e_test.go
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, release-note-none, approved

#1157 Introduce vulnerability scans for operator image
  .github/workflows/build.yml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1160 Remove CRI-O commit ID in favor of its tag
  hack/ci/install-cri-o.sh
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1161 tests: Only check the worker nodes testCaseLongSeccompProfileName
  test/tc_long_profile_name_test.go
Labels: kind/bug, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#1162 Remove restore-keys from GitHub actions cache
  .github/workflows/test.yml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1168 Bump `golang.org/x/*` to fix CVE-2022-27664
  go.mod
  go.sum
  vendor/golang.org/x/net/context/go17.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1166 Filter out host processes by host mntns to prevent ebpf map from filling up during recording
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.c
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/bpfrecorder/bpfrecorderfakes/fake_impl.go
  internal/pkg/daemon/bpfrecorder/generated.go
  internal/pkg/daemon/bpfrecorder/impl.go
Labels: kind/bug, size/XXL, release-note, cncf-cla: yes, ok-to-test, lgtm, approved

#1176 Use libbpf 1.0.0 and overlay
  nix/default-arm64.nix
  nix/default-bpf-amd64.nix
  nix/default-bpf-arm64.nix
  nix/default.nix
  nix/derivation-bpf.nix
  nix/derivation.nix
  nix/nixpkgs.json
  nix/nixpkgs.nix
  nix/overlay.nix
Labels: release-note, cncf-cla: yes, lgtm, approved, kind/cleanup, size/M

#1178 BUG 2082099: Fix finalizer string too long
  internal/pkg/nodestatus/nodestatus.go
  internal/pkg/nodestatus/nodestatus_test.go
Labels: kind/bug, release-note, cncf-cla: yes, ok-to-test, lgtm, approved, size/M
