Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2022-02, with the labels that each got.

#788 Support custom host /proc path in config
  api/spod/v1alpha1/spod_types.go
  deploy/base/crds/securityprofilesoperatordaemon.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift.yaml
  deploy/operator.yaml
  installation-usage.md
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/spod_controller.go
Labels: kind/feature, size/L, release-note, cncf-cla: yes, lgtm, approved

#740 openshift: Deploy webhook using internal CA instead of cert-manager
  Makefile
  dependencies.yaml
  deploy/openshift-dev.yaml
  deploy/openshift.yaml
  deploy/overlays/openshift/kustomization.yaml
  deploy/overlays/openshift/mutatingwebhookconfig.yaml
  deploy/overlays/openshift/no_certificate.yaml
  deploy/overlays/openshift/svc_gen_cert.yaml
Labels: size/L, release-note, cncf-cla: yes, lgtm, approved, kind/cleanup

#801 SeccompProfile CRD: add new fields for seccomp notify
  api/seccompprofile/v1beta1/seccompprofile_types.go
  deploy/base/crds/seccompprofile.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift.yaml
  deploy/operator.yaml
  internal/pkg/daemon/seccompprofile/seccompprofile.go
Labels: kind/feature, release-note, cncf-cla: yes, kind/api-change, ok-to-test, lgtm, approved, size/M

#798 Remove pinned SHA for btfhub archive
  .github/workflows/build.yml
  Makefile
  hack/update-btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/arm64/5.4.0-97-generic.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/x86_64/4.15.0-1115-gcp.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/x86_64/4.15.0-1130-azure.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/x86_64/4.15.0-167-generic.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/x86_64/5.4.0-1061-gke.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/x86_64/5.4.0-1063-gcp.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/x86_64/5.4.0-1068-azure.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/18.04/x86_64/5.4.0-97-generic.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/20.04/arm64/5.11.0-1028-azure.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/20.04/arm64/5.4.0-97-generic.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/20.04/x86_64/5.11.0-1028-azure.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/20.04/x86_64/5.11.0-1029-gcp.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/20.04/x86_64/5.4.0-1061-gke.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/20.04/x86_64/5.4.0-1063-gcp.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/20.04/x86_64/5.4.0-1068-azure.btf
  internal/pkg/daemon/bpfrecorder/btf/ubuntu/20.04/x86_64/5.4.0-97-generic.btf
  internal/pkg/daemon/bpfrecorder/generated.go
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/M

#800 Bump to v0.4.1
  VERSION
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift.yaml
  deploy/operator.yaml
Labels: kind/feature, cncf-cla: yes, size/S, lgtm, release-note-none, approved, do-not-merge/hold

#803 Bump back to dev
  VERSION
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift.yaml
  deploy/operator.yaml
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#804 Update cert-manager to v1.7.1
  dependencies.yaml
  installation-usage.md
  test/e2e_test.go
Labels: release-note, cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup

#805 Add list of bpf recorder kernels to docs
  bpf-support.md
  installation-usage.md
  internal/pkg/daemon/bpfrecorder/generate/main.go
Labels: size/XXL, release-note, cncf-cla: yes, lgtm, approved, kind/documentation

#808 doc: Provide documentation for new contributors
  README.md
  hacking.md
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation

#813 Fix binding typo and update docs
  go.sum
  installation-usage.md
  internal/pkg/manager/spod/bindata/webhook.go
Labels: release-note, cncf-cla: yes, size/S, lgtm, approved, kind/cleanup

#817 Bump third party dependencies
  .golangci.yml
  Dockerfile.build-image
  Makefile
  cmd/security-profiles-operator/main.go
  dependencies.yaml
  hack/image-cross.sh
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/grpc.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/selinuxprofile/common_controller.go
  internal/pkg/util/containers.go
  internal/pkg/webhooks/binding/binding.go
  internal/pkg/webhooks/binding/binding_test.go
  internal/pkg/webhooks/recording/recording.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup
