Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2022-11, with the labels that each got.

#1276 Fix catalog-build in `post-security-profiles-operator-push-image` job
  Makefile
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#1277 Update Kubernetes, kind and kustomize dependencies
  .github/workflows/olm_tests.yaml
  Makefile
  dependencies.yaml
  hack/ci/Vagrantfile-ubuntu
  hack/ci/install-kubernetes.sh
  test/suite_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1279 doc: Document profile-in-use finalizer usage
  installation-usage.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/documentation

#1280 enricher: Parse SELinux AVC lines that contain multiple permissions
  internal/pkg/daemon/enricher/audit.go
  internal/pkg/daemon/enricher/audit_test.go
  internal/pkg/daemon/enricher/enricher.go
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/M

#1289 Switch to `registry.k8s.io`
  Dockerfile.build-image
  dependencies.yaml
  deploy/kustomize-deployment/kustomization.yaml
  hack/ci/e2e-olm.sh
  release.md
Labels: release-note, cncf-cla: yes, size/S, lgtm, approved, kind/cleanup

#1278 selinux: Add a permissive boolean
  api/selinuxprofile/v1alpha2/selinuxprofile_types.go
  bundle/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
  deploy/base-crds/crds/selinuxpolicy.yaml
  deploy/helm/crds/crds.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  installation-usage.md
  internal/pkg/translator/obj2cil.go
  internal/pkg/translator/obj2cil_test.go
  test/e2e_test.go
  test/tc_selinux_base_usage_test.go
Labels: kind/feature, size/L, release-note, cncf-cla: yes, kind/api-change, lgtm, approved

#1299 build: Bump kube-rbac-proxy to v0.13.1
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/helm/templates/deployment.yaml
  deploy/kustomize-deployment/manager_deployment.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  internal/pkg/manager/spod/bindata/spod.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1300 Fix bundle goal into the Makefile for macos
  Makefile
Labels: release-note, cncf-cla: yes, lgtm, approved, size/XS

#1301 make: Reduce code duplication
  Makefile
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1302 apparmor: Add Flux profile
  examples/apparmorprofile-flux-controllers.yaml
Labels: release-note, cncf-cla: yes, lgtm, approved, kind/documentation, size/M

#1304 OLM: Add an OpenShift-specific annotation
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/clusterserviceversion.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1314 doc: MutatingWebhookConfiguration is not a namespaced resource
  installation-usage.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/documentation

#1309 Bump to v0.6.0
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  installation-usage.md
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation, size/M

#1317 Back to v0.6.1-dev
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  installation-usage.md
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1321 workloadannotator: Prevent crash with non-operator seccomp profiles set in annotation
  internal/pkg/manager/workloadannotator/workloadannotator.go
  internal/pkg/manager/workloadannotator/workloadannotator_test.go
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/M

#1323 Add `hack/release.sh` script
  hack/release.sh
  release.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation, size/M

#1322 Add "Using the EBPF Superpowers To Generate Kubernetes Security Policies" talk
  installation-usage.md
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/documentation

#1324 Add `make verify-in-a-container` target
  Makefile
  dependencies.yaml
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/documentation

#1328 examples: The NS must allow privileged PSS
  examples/olm/install-resources.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1326 Add `replaces` and `containerImage` to operator manifest
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/clusterserviceversion.yaml
  hack/release.sh
  release.md
Labels: release-note, cncf-cla: yes, size/S, lgtm, approved, kind/documentation

#1327 Deleting temp dir after sorting CRDs
  hack/sort-crds.sh
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1333 build: Pin GitHub actions
  .github/workflows/build.yml
  .github/workflows/helm-chart-lint.yaml
  .github/workflows/helm-chart-package.yaml
  .github/workflows/olm_tests.yaml
  .github/workflows/test.yml
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#1335 e2e-olm: The deployment manifest still points to images at gcr.io
  hack/ci/e2e-olm.sh
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#1338 Remove `hack/install-libelf.sh` script
  dependencies.yaml
  hack/install-libelf.sh
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1339 Configure the Selinux type tag when the AppArmor is disabled regardless of EnableSelinux flag
  internal/pkg/manager/spod/spod_controller.go
Labels: release-note, cncf-cla: yes, size/S, lgtm, approved

#1341 Dockerfile.ubi: Work around krb5-libs CVE until the UBI image is refreshed
  Dockerfile.ubi
  dependencies.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved
