Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2022-06, with the labels that each got.

#968 Update golangci-lint and config
  .golangci.yml
  Makefile
  dependencies.yaml
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#974 Bump nixpkgs ahead of a new release
  nix/nixpkgs.json
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#981 Bump to v0.4.3
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
Labels: kind/feature, cncf-cla: yes, size/S, lgtm, release-note-none, approved

#983 Back to v0.4.4-dev
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  release.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation, size/M

#987 Bump nix to v2.9.0
  Dockerfile.build-image
  dependencies.yaml
  hack/ci/Vagrantfile-fedora
  hack/ci/Vagrantfile-ubuntu
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#989 tests: Explicitly set the context to the SPO namespace before creating the recording SA/role/rolebinding on OCP
  test/suite_test.go
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS, kind/cleanup
