Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2022-04, with the labels that each got.

#877 Fix image-cross script
  .gcloudignore
  cloudbuild.yaml
  hack/image-cross.sh
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/M

#880 Bump to v0.4.2
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  release.md
Labels: kind/feature, cncf-cla: yes, size/S, lgtm, release-note-none, approved

#881 Back to v0.4.3-dev
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  release.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#874 Switch to golang native error wrapping
  .golangci.yml
  api/profilerecording/v1alpha1/profilerecording_types.go
  cmd/security-profiles-operator/main.go
  go.mod
  internal/pkg/daemon/apparmorprofile/apparmor_supported.go
  internal/pkg/daemon/apparmorprofile/apparmor_test.go
  internal/pkg/daemon/apparmorprofile/apparmor_unsupported.go
  internal/pkg/daemon/apparmorprofile/apparmorprofile.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/bpfrecorder/generate/main.go
  internal/pkg/daemon/bpfrecorder/impl.go
  internal/pkg/daemon/enricher/audit.go
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/grpc.go
  internal/pkg/daemon/metrics/grpc.go
  internal/pkg/daemon/metrics/metrics.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/seccompprofile/seccompprofile_test.go
  internal/pkg/daemon/selinuxprofile/common_controller.go
  internal/pkg/daemon/selinuxprofile/rawselinuxprofile.go
  internal/pkg/daemon/selinuxprofile/selinuxprofile.go
  internal/pkg/manager/nodestatus/nodestatus.go
  internal/pkg/manager/spod/bindata/ca.go
  internal/pkg/manager/spod/bindata/webhook.go
  internal/pkg/manager/spod/setup.go
  internal/pkg/manager/spod/spod_controller.go
  internal/pkg/manager/workloadannotator/setup.go
  internal/pkg/manager/workloadannotator/workloadannotator.go
  internal/pkg/nodestatus/nodestatus.go
  internal/pkg/nonrootenabler/nonrootenabler.go
  internal/pkg/util/containers.go
  internal/pkg/util/finalizers.go
  internal/pkg/util/names.go
  internal/pkg/util/reconcileutils_test.go
  internal/pkg/util/retries.go
  internal/pkg/version/version.go
  internal/pkg/webhooks/binding/binding.go
  internal/pkg/webhooks/binding/binding_test.go
  internal/pkg/webhooks/binding/impl.go
  internal/pkg/webhooks/recording/impl.go
  internal/pkg/webhooks/recording/recording.go
  internal/pkg/webhooks/utils/utils.go
  internal/pkg/webhooks/utils/utils_test.go
  test/tc_selinux_base_usage_test.go
Labels: cncf-cla: yes, size/XL, lgtm, release-note-none, approved, kind/cleanup

#854 Add Support for Selinux Profile Binding
  api/profilebinding/v1alpha1/profilebinding_types.go
  api/selinuxprofile/v1alpha2/selinuxprofile_types.go
  api/selinuxprofile/v1alpha2/zz_generated.deepcopy.go
  bundle/manifests/security-profiles-operator.x-k8s.io_profilebindings.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
  bundle/manifests/spo-webhook_rbac.authorization.k8s.io_v1_clusterrole.yaml
  cmd/security-profiles-operator/main.go
  deploy/base/crd.yaml
  deploy/base/crds/profilebinding.yaml
  deploy/base/crds/selinuxpolicy.yaml
  deploy/base/role.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  internal/pkg/manager/workloadannotator/setup.go
  internal/pkg/manager/workloadannotator/workloadannotator.go
  internal/pkg/webhooks/binding/binding.go
  internal/pkg/webhooks/binding/binding_test.go
  internal/pkg/webhooks/binding/bindingfakes/fake_impl.go
  internal/pkg/webhooks/binding/impl.go
  test/e2e_test.go
  test/tc_seccomp_profilebindings_test.go
  test/tc_selinux_profilebindings_test.go
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, ok-to-test, lgtm, approved

#886 Bump cert-manager to v1.8.0
  dependencies.yaml
  hack/ci/e2e-olm.sh
  installation-usage.md
  test/e2e_test.go
Labels: size/L, release-note, cncf-cla: yes, lgtm, approved, kind/cleanup

#884 bundle: Add an icon
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/clusterserviceversion.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#883 Make webhooks' failurePolicy and namespaceSelector configurable
  api/spod/v1alpha1/spod_types.go
  api/spod/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
  deploy/base/crds/securityprofilesoperatordaemon.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  installation-usage.md
  internal/pkg/manager/spod/bindata/webhook.go
  internal/pkg/manager/spod/spod_controller.go
  test/e2e_test.go
  test/tc_webhook_config_test.go
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, lgtm, approved

#892 fix: make the webhook tolerations configurable
  internal/pkg/manager/spod/bindata/webhook.go
  internal/pkg/manager/spod/spod_controller.go
Labels: release-note, cncf-cla: yes, ok-to-test, lgtm, approved, size/XS

#896 Fix missing key/value for profile not found log message
  internal/pkg/daemon/profilerecorder/profilerecorder.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#895 docs: Clarify details on seccomp recording
  installation-usage.md
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/documentation

#894 docs: Use kubectl logs --selector name=spod instead kubectl logs ds/spod
  installation-usage.md
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/documentation

#846 Add ability to patch "problematic" pods
  api/spod/v1alpha1/spod_types.go
  bundle/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
  bundle/manifests/spod_rbac.authorization.k8s.io_v1_clusterrole.yaml
  cmd/security-profiles-operator/main.go
  deploy/base/crds/securityprofilesoperatordaemon.yaml
  deploy/base/role.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/operator.yaml
  go.mod
  hack/ci/e2e-fedora.sh
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/enricher/enricherfakes/fake_impl.go
  internal/pkg/daemon/enricher/impl.go
  internal/pkg/manager/spod/spod_controller.go
  test/e2e_test.go
  test/suite_test.go
  test/tc_selinux_label_problematic_test.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, kind/api-change, lgtm, approved, kind/design

#899 Fix CSV annotations: operatorframework.io/suggested-namespace
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/clusterserviceversion.yaml
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/XS
