Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2022-07, with the labels that each got.

#1022 Update build image versions
  Dockerfile.build-image
  dependencies.yaml
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1021 Update cloudbuild image
  cloudbuild.yaml
  dependencies.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1023 Update kube-rbac-proxy to v0.13.0
  dependencies.yaml
  internal/pkg/manager/spod/bindata/spod.go
Labels: release-note, cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup

#1024 Update CRI-O to v1.24.1
  dependencies.yaml
  hack/ci/install-cri-o.sh
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1020 Update Kubernetes to v1.24.3
  dependencies.yaml
  hack/ci/Vagrantfile-ubuntu
  hack/ci/install-kubernetes.sh
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1040 Verify CRI-O signatures and SBOM
  dependencies.yaml
  hack/ci/install-cri-o.sh
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1045 Use operator-sdk v1.22.2
  Makefile
  bundle.Dockerfile
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  dependencies.yaml
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1054 Switch to macos-12 runners
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1055 deploy: make sure that manifests start with a separator
  deploy/base/clusterserviceversion.yaml
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#1043 Bump cert-manager to v1.9.1
  dependencies.yaml
  hack/ci/e2e-olm.sh
  installation-usage.md
  test/e2e_test.go
Labels: release-note, cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup

#1061 Switch to ttlcache v3
  .golangci.yml
  go.mod
  go.sum
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/bpfrecorder/bpfrecorderfakes/fake_impl.go
  internal/pkg/daemon/bpfrecorder/impl.go
  internal/pkg/daemon/enricher/audit.go
  internal/pkg/daemon/enricher/audit_test.go
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/enricher/enricherfakes/fake_impl.go
  internal/pkg/daemon/enricher/impl.go
  internal/pkg/daemon/enricher/types/types.go
  internal/pkg/util/containers.go
  vendor/github.com/ReneKroon/ttlcache/v2/.travis.yml
  vendor/github.com/ReneKroon/ttlcache/v2/Readme.md
  vendor/github.com/ReneKroon/ttlcache/v2/cache.go
  vendor/github.com/ReneKroon/ttlcache/v2/evictionreason_enumer.go
  vendor/github.com/ReneKroon/ttlcache/v2/item.go
  vendor/github.com/ReneKroon/ttlcache/v2/metrics.go
  vendor/github.com/ReneKroon/ttlcache/v2/priority_queue.go
  vendor/github.com/jellydator/ttlcache/v3/CHANGELOG.md
  vendor/github.com/jellydator/ttlcache/v3/LICENSE
  vendor/github.com/jellydator/ttlcache/v3/README.md
  vendor/github.com/jellydator/ttlcache/v3/cache.go
  vendor/github.com/jellydator/ttlcache/v3/expiration_queue.go
  vendor/github.com/jellydator/ttlcache/v3/item.go
  vendor/github.com/jellydator/ttlcache/v3/metrics.go
  vendor/github.com/jellydator/ttlcache/v3/options.go
  vendor/modules.txt
Labels: size/XXL, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup
