Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2023-11, with the labels that each got.

#1966 Disable e2e tests for now
  .github/workflows/helm-chart-lint.yaml
  .github/workflows/test.yml
  test/e2e_test.go
  test/tc_base_profiles_oci_test.go
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/M

#1940 Use kube-rbac-proxy v0.15.0 and disable HTTP/2
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/helm/templates/deployment.yaml
  deploy/kustomize-deployment/manager_deployment.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  internal/pkg/manager/spod/bindata/spod.go
Labels: kind/bug, release-note, cncf-cla: yes, size/S, ok-to-test, lgtm, approved

#1928 OCPBUGS-22182:Fix nodestatus missing issue
  internal/pkg/nodestatus/nodestatus.go
Labels: kind/bug, release-note, cncf-cla: yes, lgtm, approved, size/XS

#1956 Avoid listing pods in the recording webhook handler which leads sometimes to a webhook timeout issue
  internal/pkg/webhooks/recording/recording.go
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/M

#1970 Bump dependencies
  .github/workflows/build.yml
  .golangci.yml
  Dockerfile.build-image
  Makefile
  cloudbuild.yaml
  dependencies.yaml
  hack/ci/Vagrantfile-ubuntu
  hack/ci/baseprofiles.sh
  hack/ci/e2e-olm.sh
  installation-usage.md
  test/e2e_test.go
  test/tc_bpf_recorder_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1923 Use http/1.1 for webhooks, metrics and profiling endpoints
  cmd/security-profiles-operator/main.go
  test/e2e_flaky_test.go
  test/e2e_test.go
  test/suite_test.go
  test/tc_bpf_recorder_test.go
  test/tc_log_enricher_test.go
  test/tc_metrics_test.go
  test/tc_profiling_test.go
  test/tc_webhook_config_test.go
Labels: kind/bug, size/L, cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved

#1984 Update nixpkgs
  nix/nixpkgs.json
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1985 Fix namespace selector comparison for webhook
  internal/pkg/manager/spod/bindata/webhook.go
  internal/pkg/manager/spod/bindata/webhook_test.go
  internal/pkg/manager/spod/spod_controller.go
Labels: kind/bug, size/L, release-note, cncf-cla: yes, lgtm, approved

#1990 Bump to v0.8.1
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/base/clusterserviceversion.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M
