Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2023-01, with the labels that each got.

#1406 Update bundle to match latest year
  api/apparmorprofile/v1alpha1/zz_generated.deepcopy.go
  api/profilebinding/v1alpha1/zz_generated.deepcopy.go
  api/profilerecording/v1alpha1/zz_generated.deepcopy.go
  api/seccompprofile/v1beta1/zz_generated.deepcopy.go
  api/secprofnodestatus/v1alpha1/zz_generated.deepcopy.go
  api/selinuxprofile/v1alpha2/zz_generated.deepcopy.go
  api/spod/v1alpha1/zz_generated.deepcopy.go
Labels: cncf-cla: yes, kind/failing-test, size/S, lgtm, release-note-none, approved

#1417 Switch to flatcar beta vagrant box
  dependencies.yaml
  hack/ci/Vagrantfile-flatcar
Labels: cncf-cla: yes, kind/failing-test, size/S, lgtm, release-note-none, approved

#1382 e2e: Wait for profile that is supposed to be used
  test/tc_seccomp_profilebindings_test.go
Labels: cncf-cla: yes, kind/flake, lgtm, release-note-none, approved, size/XS

#1384 bundle: Add OCP-specific cluster monitoring annotation
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/clusterserviceversion.yaml
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#1361 Remove nginx default profile
  examples/pod.yaml
  go.mod
  internal/pkg/manager/spod/bindata/default_profiles.go
  internal/pkg/manager/spod/spod_controller.go
  test/e2e_test.go
  test/suite_test.go
  test/tc_default_profiles_test.go
  test/tc_run_pod_test.go
Labels: size/L, release-note, cncf-cla: yes, kind/deprecation, lgtm, approved

#1424 Use non-legacy method to install apt key for Ubuntu
  hack/ci/Vagrantfile-ubuntu
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1429 Switch to `gcr.io/kubebuilder/kube-rbac-proxy`
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/helm/templates/deployment.yaml
  deploy/kustomize-deployment/manager_deployment.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  hack/release.sh
  internal/pkg/manager/spod/bindata/spod.go
  test/e2e_test.go
Labels: release-note, cncf-cla: yes, lgtm, approved, kind/documentation, size/M

#1396 Exposing spo image repo & tag in helm charts to make it configurable
  deploy/helm/templates/deployment.yaml
  deploy/helm/values.yaml
Labels: release-note, cncf-cla: yes, ok-to-test, lgtm, approved, size/XS

#1434 Add syscalls to operator seccomp profile
  bundle/manifests/security-profiles-operator-profile_v1_configmap.yaml
  deploy/base/profiles/security-profiles-operator.json
  deploy/helm/templates/static-resources.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
Labels: kind/bug, release-note, cncf-cla: yes, lgtm, approved, size/M

#1437 Apply context check linter
  .golangci.yml
  internal/pkg/daemon/apparmorprofile/apparmorprofile.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/selinuxprofile/common_controller.go
  internal/pkg/manager/nodestatus/nodestatus.go
  internal/pkg/manager/recordingmerger/recordingmerger.go
  internal/pkg/manager/spod/spod_controller.go
  internal/pkg/manager/workloadannotator/setup.go
  internal/pkg/manager/workloadannotator/workloadannotator.go
  internal/pkg/nodestatus/nodestatus.go
  internal/pkg/version/version.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup
