Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2023-03, with the labels that each got.

#1513 Pin nix version in GitHub actions to fix builds
  .github/workflows/build.yml
  Dockerfile.build-image
  dependencies.yaml
Labels: cncf-cla: yes, kind/failing-test, size/S, lgtm, release-note-none, approved

#1510 Add base syscalls for spoc recording
  cmd/spoc/main.go
  internal/pkg/cli/recorder/consts.go
  internal/pkg/cli/recorder/options.go
  internal/pkg/cli/recorder/recorder.go
Labels: kind/feature, size/L, release-note, cncf-cla: yes, lgtm, approved

#1514 Add test stubs to `spoc record`
  internal/pkg/cli/recorder/impl.go
  internal/pkg/cli/recorder/recorder.go
  internal/pkg/cli/recorder/recorder_test.go
  internal/pkg/cli/recorder/recorderfakes/fake_impl.go
Labels: size/XXL, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#1524 Promote ccojocar to become approver
  OWNERS
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/documentation

#991 Create baseprofiles in CI
  .github/workflows/test.yml
  dependencies.yaml
  examples/baseprofile-crun.yaml
  examples/baseprofile-runc.yaml
  hack/ci/baseprofiles.sh
  hack/ci/install-cri-o.sh
  hack/deploy-localhost.patch
  internal/pkg/cli/recorder/consts.go
  test/tc_base_profiles_test.go
Labels: kind/feature, size/L, cncf-cla: yes, lgtm, release-note-none, approved

#1529 Bump cosign to v2.0.0
  dependencies.yaml
  hack/ci/install-cri-o.sh
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1530 Reformat docs to fix markdown
  installation-usage.md
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation

#1533 Always use filepath.Base for command filter
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#1536 Add `spoc` documentation
  installation-usage.md
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation

#1523 Add unit tests to cli recorder
  internal/pkg/cli/recorder/recorder_test.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#1540 Provide build binaries via GitHub actions
  .github/workflows/build.yml
  .gitignore
  Makefile
Labels: kind/feature, cncf-cla: yes, size/S, lgtm, release-note-none, approved

#1539 Bump kind Kubernetes image to v1.26.2
  .github/workflows/olm_tests.yaml
  dependencies.yaml
  test/suite_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1543 Fix memory optimisation feature after upgrade to controller-runtime v0.14.5
  cmd/security-profiles-operator/main.go
Labels: kind/bug, release-note, cncf-cla: yes, size/S, lgtm, approved

#1545 Integrate enricher into `spoc run`
  cmd/spoc/main.go
  internal/pkg/cli/consts.go
  internal/pkg/cli/recorder/consts.go
  internal/pkg/cli/recorder/logsink.go
  internal/pkg/cli/recorder/recorder.go
  internal/pkg/cli/runner/consts.go
  internal/pkg/cli/runner/impl.go
  internal/pkg/cli/runner/options.go
  internal/pkg/cli/runner/runner.go
  internal/pkg/cli/runner/runner_test.go
  internal/pkg/cli/runner/runnerfakes/fake_impl.go
  internal/pkg/daemon/enricher/audit.go
  internal/pkg/daemon/enricher/audit_test.go
  internal/pkg/daemon/enricher/enricher.go
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, lgtm, approved

#1542 Init the README.md for spo
  deploy/helm/README.md
  deploy/helm/templates/_helpers.tpl
  deploy/helm/templates/config.yaml
  deploy/helm/templates/deployment.yaml
Labels: release-note, cncf-cla: yes, ok-to-test, lgtm, approved, kind/documentation, size/M

#1549 Cleanup enricher init
  cmd/security-profiles-operator/main.go
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1380 merging: Fix the mergeStrategy=containers option
  internal/pkg/manager/recordingmerger/merge_utils.go
  internal/pkg/manager/recordingmerger/recordingmerger.go
  test/tc_profilemerging_test.go
  test/tc_profilerecordings_test.go
Labels: kind/bug, size/L, release-note, cncf-cla: yes, lgtm, approved

#1558 Fix typo in variable name
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/spod_controller.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1563 Back to dev
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  installation-usage.md
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1568 Fix: namespace resource should not be defined in the helm chart
  deploy/helm/templates/static-resources.yaml
  deploy/overlays/helm/delete-ns.yaml
  deploy/overlays/helm/kustomization.yaml
Labels: kind/bug, release-note, cncf-cla: yes, ok-to-test, lgtm, approved, size/M

#1570 Update UBI image to fix CVE-2023-0286
  Dockerfile.ubi
  dependencies.yaml
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#1569 Bump to v0.7.1
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/base/clusterserviceversion.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  installation-usage.md
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1575 Back to dev
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation, size/M

#1579 Update zeitgeist to v0.4.1
  Makefile
  dependencies.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1559 Verify that base profiles exist in GitHub container registry
  hack/ci/baseprofiles.sh
Labels: kind/feature, cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#1581 Remove `OutputProfile` type
  internal/pkg/config/config.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/seccompprofile/seccompprofile_test.go
  test/tc_default_profiles_test.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#1589 Add `oci://` security profiles badge
  README.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/documentation

#1586 Update CRI-O and runc/crun base profiles
  dependencies.yaml
  examples/baseprofile-crun.yaml
  examples/baseprofile-runc.yaml
  hack/ci/install-cri-o.sh
  installation-usage.md
  test/tc_base_profiles_test.go
Labels: release-note, cncf-cla: yes, size/S, lgtm, approved, kind/cleanup

#1587 Use mergo for syscall merge
  go.mod
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/seccompprofile/seccompprofile_test.go
  internal/pkg/manager/recordingmerger/merge_utils.go
  internal/pkg/manager/recordingmerger/merge_utils_test.go
  internal/pkg/util/union_syscalls.go
  internal/pkg/util/union_syscalls_test.go
Labels: kind/bug, size/L, release-note, cncf-cla: yes, lgtm, approved
