Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2023-04, with the labels that each got.

#1594 Add signed spoc binary to GitHub actions
  .github/workflows/build.yml
  Makefile
  nix/default-spoc-amd64.nix
  nix/default-spoc-arm64.nix
  nix/derivation.nix
Labels: kind/feature, cncf-cla: yes, lgtm, release-note-none, approved, size/M

#1595 Sync seccomp base profiles with spoc
  internal/pkg/cli/recorder/consts.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1596 Switch from N1 to E2 machine for cloudbuild
  cloudbuild.yaml
Labels: cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1597 Fix typo in GitHub action
  .github/workflows/build.yml
  Makefile
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#1599 Attach Bill of Materials to spoc artifacts
  .github/workflows/build.yml
  Makefile
  dependencies.yaml
  hack/ci/install-cri-o.sh
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/documentation

#1600 Auto-select selinuxd image based on nodeInfo.OSImage
  bundle/manifests/security-profiles-operator-profile_v1_configmap.yaml
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/kustomization.yaml
  deploy/base/profiles/selinuxd-image-mapping.json
  deploy/base/role.yaml
  deploy/helm/templates/static-resources.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/overlays/webhook/role.yaml
  deploy/webhook-operator.yaml
  internal/pkg/manager/spod/setup.go
  internal/pkg/manager/spod/spod_controller.go
  internal/pkg/util/constants.go
  internal/pkg/util/kubernetes.go
  internal/pkg/util/kubernetes_test.go
Labels: kind/feature, size/L, release-note, cncf-cla: yes, lgtm, approved

#1603 Wait a second before stopping `spoc run`
  internal/pkg/cli/runner/runner.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1605 Update golangci-lint and config
  .golangci.yml
  Makefile
  dependencies.yaml
  internal/pkg/cli/logsink.go
  internal/pkg/daemon/apparmorprofile/apparmor_supported.go
  internal/pkg/daemon/apparmorprofile/apparmor_unsupported.go
  internal/pkg/daemon/apparmorprofile/apparmorprofile_test.go
  internal/pkg/daemon/apparmorprofile/setup.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_unsupported.go
  internal/pkg/daemon/bpfrecorder/generate/main.go
  internal/pkg/daemon/enricher/container.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/enricher/grpc.go
  internal/pkg/daemon/enricher/syscall_unsupported.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/seccompprofile/impl.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/selinuxprofile/common_controller.go
  internal/pkg/manager/nodestatus/setup.go
  internal/pkg/manager/spod/bindata/ca.go
  internal/pkg/manager/spod/bindata/webhook.go
  internal/pkg/manager/spod/setup.go
  internal/pkg/manager/spod/spod_controller.go
  internal/pkg/manager/workloadannotator/setup.go
  internal/pkg/manager/workloadannotator/workloadannotator.go
  internal/pkg/util/mock_client.go
  internal/pkg/webhooks/utils/utils_test.go
  test/suite_test.go
  test/tc_base_profiles_oci_test.go
  test/tc_base_profiles_test.go
  test/tc_enable_profile_recorder_test.go
  test/tc_metrics_test.go
  test/tc_spod_update_selinux_test.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#1606 Switch from `actions/upload-release-asset` to `softprops/action-gh-release
  .github/workflows/helm-chart-package.yaml
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1607 Update nixpkgs
  Makefile
  hack/install-packages
  hack/pull-security-profiles-operator-build
  hack/pull-security-profiles-operator-test-unit
  hack/pull-security-profiles-operator-verify
  nix/derivation.nix
  nix/nixpkgs.json
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1616 Update cert-manager to v1.11.1
  dependencies.yaml
  hack/ci/baseprofiles.sh
  hack/ci/e2e-olm.sh
  installation-usage.md
  test/e2e_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1621 Bump CI Kubernetes to v1.27.0
  .github/workflows/olm_tests.yaml
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/helm/templates/deployment.yaml
  deploy/kustomize-deployment/manager_deployment.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  hack/ci/Vagrantfile-ubuntu
  hack/ci/install-kubernetes.sh
  internal/pkg/manager/spod/bindata/spod.go
  test/suite_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1615 Fix ebpf recorder log typo
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/documentation

#1631 Bump to v0.8.0
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/base/clusterserviceversion.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation, size/M

#1636 Bump back to dev
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1634 ci: switch back to flatcar stable
  dependencies.yaml
  hack/ci/Vagrantfile-flatcar
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1642 Make the selinuxd auto-selection logic use environment variables
  bundle/manifests/security-profiles-operator-profile_v1_configmap.yaml
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/profiles/selinuxd-image-mapping.json
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/static-resources.yaml
  deploy/kustomize-deployment/manager_deployment.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  internal/pkg/manager/spod/setup.go
  internal/pkg/util/kubernetes.go
  internal/pkg/util/kubernetes_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1635 Run build workflow on tags as well
  .github/workflows/build.yml
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#1647 Allow empty `HostProcVolumePath`
  internal/pkg/manager/spod/spod_controller.go
Labels: kind/bug, release-note, cncf-cla: yes, lgtm, approved, size/XS

#1648 Patching container ID discovery to support DiD
  internal/pkg/util/containers.go
Labels: kind/bug, release-note, cncf-cla: yes, ok-to-test, lgtm, approved, size/XS

#1650 Bump CRI-O to v1.27.0 and update base profiles
  dependencies.yaml
  examples/baseprofile-crun.yaml
  examples/baseprofile-runc.yaml
  hack/ci/baseprofiles.sh
  hack/ci/install-cri-o.sh
  installation-usage.md
  test/tc_base_profiles_test.go
Labels: release-note, cncf-cla: yes, lgtm, approved, kind/cleanup, size/M
