Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2023-05, with the labels that each got.

#1658 Add OCI artifact platform support
  cmd/spoc/main.go
  installation-usage.md
  internal/pkg/artifact/artifact.go
  internal/pkg/artifact/artifact_test.go
  internal/pkg/cli/consts.go
  internal/pkg/cli/platform.go
  internal/pkg/cli/platform_test.go
  internal/pkg/cli/puller/consts.go
  internal/pkg/cli/puller/impl.go
  internal/pkg/cli/puller/options.go
  internal/pkg/cli/puller/puller.go
  internal/pkg/cli/puller/pullerfakes/fake_impl.go
  internal/pkg/cli/pusher/consts.go
  internal/pkg/cli/pusher/impl.go
  internal/pkg/cli/pusher/options.go
  internal/pkg/cli/pusher/options_test.go
  internal/pkg/cli/pusher/pusher.go
  internal/pkg/cli/pusher/pusherfakes/fake_impl.go
  internal/pkg/cli/runner/consts.go
  internal/pkg/daemon/seccompprofile/impl.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/seccompprofile/seccompprofilefakes/fake_impl.go
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, lgtm, approved

#1677 Update kustomize to v5.0.3
  Makefile
  dependencies.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1676 Use dl.k8s.io instead of the `kubernetes-release` bucket
  hack/ci/Vagrantfile-flatcar
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1670 Bump libbpf and libbpf-go
  dependencies.yaml
  go.mod
  go.sum
  hack/install-libbpf.sh
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorderfakes/fake_impl.go
  internal/pkg/daemon/bpfrecorder/impl.go
  vendor/github.com/aquasecurity/libbpfgo/.clang-format
  vendor/github.com/aquasecurity/libbpfgo/.clang-tidy
  vendor/github.com/aquasecurity/libbpfgo/.revive.toml
  vendor/github.com/aquasecurity/libbpfgo/Makefile
  vendor/github.com/aquasecurity/libbpfgo/Readme.md
  vendor/github.com/aquasecurity/libbpfgo/elf.go
  vendor/github.com/aquasecurity/libbpfgo/libbpf_cb.go
  vendor/github.com/aquasecurity/libbpfgo/libbpfgo.go
  vendor/github.com/aquasecurity/libbpfgo/libbpfgo.h
  vendor/github.com/aquasecurity/libbpfgo/logger_cb.go
  vendor/modules.txt
Labels: size/XXL, release-note, cncf-cla: yes, lgtm, approved, kind/cleanup

#1697 Fix Kubernetes install on Ubuntu VM
  hack/ci/Vagrantfile-ubuntu
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#1687 Update kind and Kubernetes images
  .github/workflows/olm_tests.yaml
  dependencies.yaml
  hack/ci/Vagrantfile-ubuntu
  hack/ci/install-kubernetes.sh
  test/suite_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1709 Update external dependencies
  .github/workflows/build.yml
  .github/workflows/olm_tests.yaml
  Dockerfile.build-image
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  cloudbuild.yaml
  dependencies.yaml
  deploy/helm/templates/deployment.yaml
  deploy/kustomize-deployment/manager_deployment.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  hack/ci/baseprofiles.sh
  hack/ci/e2e-olm.sh
  hack/ci/install-audit2rbac.sh
  installation-usage.md
  internal/pkg/manager/spod/bindata/spod.go
  nix/nixpkgs.json
  test/e2e_test.go
  test/suite_test.go
Labels: release-note, cncf-cla: yes, lgtm, approved, kind/cleanup, size/M

#1710 Fix string comparison on not found resources
  internal/pkg/manager/spod/bindata/ca.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1712 Recorded profiles can optionally be disabled after creation
  api/apparmorprofile/v1alpha1/apparmorprofile_types.go
  api/apparmorprofile/v1alpha1/zz_generated.deepcopy.go
  api/profilebase/v1alpha1/profilebase.go
  api/profilerecording/v1alpha1/profilerecording_types.go
  api/seccompprofile/v1beta1/seccompprofile_types.go
  api/seccompprofile/v1beta1/zz_generated.deepcopy.go
  api/secprofnodestatus/v1alpha1/secprofnodestatus_types.go
  api/selinuxprofile/v1alpha2/rawselinuxprofile_types.go
  api/selinuxprofile/v1alpha2/selinuxprofile_types.go
  api/selinuxprofile/v1alpha2/zz_generated.deepcopy.go
  bundle/manifests/security-profiles-operator.x-k8s.io_profilerecordings.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
  deploy/base-crds/crds/profilerecording.yaml
  deploy/base-crds/crds/seccompprofile.yaml
  deploy/base-crds/crds/selinuxpolicy.yaml
  deploy/helm/crds/crds.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  installation-usage.md
  internal/pkg/daemon/profilerecorder/impl.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/profilerecorder/profilerecorder_test.go
  internal/pkg/daemon/profilerecorder/profilerecorderfakes/fake_impl.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/selinuxprofile/common_controller.go
  internal/pkg/manager/nodestatus/nodestatus.go
  internal/pkg/nodestatus/nodestatus.go
  test/e2e_test.go
  test/tc_profilemerging_test.go
  test/tc_selinux_base_usage_test.go
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, kind/api-change, lgtm, approved
