Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2023-09, with the labels that each got.

#1853 Use official packages for Fedora machine
  .github/workflows/test.yml
  dependencies.yaml
  hack/ci/Vagrantfile-fedora
  hack/ci/Vagrantfile-ubuntu
  hack/ci/env-fedora.sh
  hack/ci/env.sh
  hack/ci/install-audit2rbac.sh
  hack/ci/install-kubernetes.sh
  hack/ci/print-rbac.sh
  hack/ci/run-fedora.sh
  hack/ci/run-ubuntu.sh
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#1854 Switch to go 1.21
  .github/workflows/build.yml
  .github/workflows/olm_tests.yaml
  .github/workflows/test.yml
  Makefile
  dependencies.yaml
  go.mod
  go.sum
  hack/ci/Vagrantfile-fedora
  hack/ci/Vagrantfile-flatcar
  hack/ci/Vagrantfile-ubuntu
  nix/derivation-bpf.nix
  nix/derivation.nix
  nix/nixpkgs.json
Labels: size/L, release-note, cncf-cla: yes, lgtm, approved, kind/cleanup

#1867 Bump clang version
  dependencies.yaml
  internal/pkg/daemon/bpfrecorder/generated.go
  nix/derivation-bpf.nix
Labels: size/XXL, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#1866 Remove OTEL override in go.mod
  go.mod
  go.sum
  vendor/go.opentelemetry.io/otel/metric/asyncfloat64.go
  vendor/go.opentelemetry.io/otel/metric/asyncint64.go
  vendor/go.opentelemetry.io/otel/metric/doc.go
  vendor/go.opentelemetry.io/otel/metric/instrument.go
  vendor/go.opentelemetry.io/otel/metric/meter.go
  vendor/go.opentelemetry.io/otel/metric/syncfloat64.go
  vendor/go.opentelemetry.io/otel/metric/syncint64.go
  vendor/modules.txt
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#1889 OCPBUGS-19744: Add RawSelinuxProfile type to the known type
  internal/pkg/manager/nodestatus/nodestatus.go
Labels: kind/bug, release-note, cncf-cla: yes, lgtm, approved, size/XS

#1888 Use CRI-O package repo instead of `get` script
  dependencies.yaml
  examples/baseprofile-crun.yaml
  hack/ci/Vagrantfile-fedora
  hack/ci/Vagrantfile-ubuntu
  hack/ci/install-cri-o.sh
  hack/ci/install-kubernetes.sh
  test/tc_base_profiles_test.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup
