Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2023-12, with the labels that each got.

#1994 Fixes getting owner profile: the node status owner is of an unknown kind AppArmorProfile
  internal/pkg/manager/nodestatus/nodestatus.go
Labels: cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, size/XS

#2023 OCPBUGS-25373: Revert "Use `metav1.Condition` type directly"
  api/spod/v1alpha1/spod_types.go
  api/spod/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
  deploy/base-crds/crds/seccompprofile.yaml
  deploy/base-crds/crds/securityprofilesoperatordaemon.yaml
  deploy/base-crds/crds/selinuxpolicy.yaml
  deploy/helm/crds/crds.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  internal/pkg/manager/spod/spod_controller.go
Labels: kind/bug, size/XXL, release-note, cncf-cla: yes, kind/failing-test, kind/regression, ok-to-test, lgtm, approved

#2030 Bump to v0.8.2
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/base/clusterserviceversion.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#2032 Back to dev
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#2033 Make field disabling profiles after recording optional
  api/profilebase/v1alpha1/profilebase.go
  api/profilerecording/v1alpha1/profilerecording_types.go
  bundle/manifests/security-profiles-operator.x-k8s.io_profilerecordings.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
  deploy/base-crds/crds/profilerecording.yaml
  deploy/base-crds/crds/seccompprofile.yaml
  deploy/base-crds/crds/selinuxpolicy.yaml
  deploy/helm/crds/crds.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
Labels: kind/bug, release-note, cncf-cla: yes, needs-ok-to-test, kind/regression, lgtm, approved, size/M
