Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2023-10, with the labels that each got.

#1900 Bump crun to v1.9.2
  dependencies.yaml
  examples/baseprofile-crun.yaml
  test/tc_base_profiles_test.go
Labels: release-note, cncf-cla: yes, lgtm, approved, size/XS, kind/cleanup

#1904 OCPBUGS-17164: Fix SelinuxProfile inherit issue
  internal/pkg/daemon/selinuxprofile/selinuxprofile.go
  internal/pkg/daemon/selinuxprofile/selinuxprofile_test.go
Labels: kind/bug, release-note, cncf-cla: yes, size/S, ok-to-test, lgtm, approved

#1919 OCPBUGS-17164: Fix SELinuxprofile inherit issue
  internal/pkg/translator/obj2cil.go
  internal/pkg/translator/obj2cil_test.go
Labels: kind/bug, release-note, cncf-cla: yes, size/S, lgtm, approved

#1927 Update crun to 1.10
  .github/workflows/test.yml
  Dockerfile.ubi
  dependencies.yaml
  examples/baseprofile-crun.yaml
  test/tc_base_profiles_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1937 Use latest golang in Vagrant based tests
  .github/workflows/test.yml
  dependencies.yaml
  hack/ci/Vagrantfile-fedora
  hack/ci/Vagrantfile-flatcar
  hack/ci/Vagrantfile-ubuntu
  hack/ci/install-kubernetes.sh
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M
