Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2023-06, with the labels that each got.

#1724 Add OpenSourceSummit 2023 (ContainerCon) talk link
  installation-usage.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#1727 Update golangci-lint and config
  .golangci.yml
  Makefile
  dependencies.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1731 Add OSFF scorecard action
  .github/workflows/osff.yml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#1756 Fix e2e tests
  test/tc_base_profiles_oci_test.go
Labels: cncf-cla: yes, kind/failing-test, size/S, lgtm, release-note-none, approved

#1761 Switch to clang 14 for debian based tests
  dependencies.yaml
  hack/pull-security-profiles-operator-verify
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS
