Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2023-02, with the labels that each got.

#1447 Mount the custom kubelet root directory into non-root-enabler container when is different from default
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/spod_controller.go
Labels: kind/bug, release-note, cncf-cla: yes, size/S, lgtm, approved

#1450 Update the kubelet volume mount of non-root enabler container on the real object not on a copy of it
  internal/pkg/manager/spod/spod_controller.go
Labels: kind/bug, release-note, cncf-cla: yes, lgtm, approved, size/XS

#1449 Switch to go 1.20 for CI jobs
  .github/workflows/build.yml
  .github/workflows/olm_tests.yaml
  .github/workflows/test.yml
  Makefile
  dependencies.yaml
  hack/ci/Vagrantfile-fedora
  hack/ci/Vagrantfile-flatcar
  hack/ci/Vagrantfile-ubuntu
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1455 Update kustomize to v5.0.0
  Makefile
  dependencies.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1456 Remove `python3` from `pull-security-profiles-operator-verify`
  hack/pull-security-profiles-operator-verify
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1463 Update golangci-lint and config
  .golangci.yml
  Makefile
  dependencies.yaml
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/selinuxprofile/common_controller.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1466 Bump UBI images
  Dockerfile.ubi
  dependencies.yaml
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#1465 Update qemu to v7.2.0-1
  dependencies.yaml
  hack/image-cross.sh
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1489 Update clang, nix and golang for nix
  Dockerfile.build-image
  dependencies.yaml
  go.mod
  hack/pull-security-profiles-operator-verify
  internal/pkg/daemon/bpfrecorder/generated.go
  nix/derivation-bpf.nix
  nix/derivation.nix
  nix/nixpkgs.json
Labels: size/XXL, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#1490 Add `spoc`, the Security Profiles Operator CLI
  Dockerfile
  Dockerfile.ubi
  Makefile
  cmd/cmd.go
  cmd/security-profiles-operator/main.go
  cmd/spoc/main.go
  cmd/spoc/record.go
  nix/derivation.nix
Labels: kind/feature, size/L, release-note, cncf-cla: yes, lgtm, approved

#1492 Wrap the `spoc` CLI from the operator
  Dockerfile
  cmd/security-profiles-operator/main.go
Labels: kind/feature, release-note, cncf-cla: yes, size/S, lgtm, approved

#1376 Exposing values to enable users to manage the SecurityProfilesOperatorDaemon config
  deploy/helm/templates/config.yaml
  deploy/helm/values.yaml
Labels: release-note, cncf-cla: yes, size/S, ok-to-test, lgtm, approved

#1493 Update debian-base image to v1.4.3
  Dockerfile.build-image
  dependencies.yaml
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1495 selinux: Allow using other container-selinux policy templates than container
  internal/pkg/translator/obj2cil.go
  internal/pkg/translator/obj2cil_test.go
  test/e2e_test.go
  test/suite_test.go
  test/tc_selinux_base_usage_test.go
Labels: kind/bug, release-note, cncf-cla: yes, lgtm, approved, size/M

#1497 Add support for recording seccomp profiles via `spoc`
  .golangci.yml
  Makefile
  cmd/spoc/main.go
  go.mod
  go.sum
  internal/pkg/cli/recorder/bpf/recorder.bpf.c
  internal/pkg/cli/recorder/generate/main.go
  internal/pkg/cli/recorder/generated.go
  internal/pkg/cli/recorder/recorder.go
  internal/pkg/cli/recorder/recorder_unsupported.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/util/convert.go
  nix/derivation-bpf.nix
  vendor/github.com/liggitt/tabwriter/.travis.yml
  vendor/github.com/liggitt/tabwriter/LICENSE
  vendor/github.com/liggitt/tabwriter/README.md
  vendor/github.com/liggitt/tabwriter/tabwriter.go
  vendor/k8s.io/apimachinery/pkg/util/duration/duration.go
  vendor/k8s.io/cli-runtime/LICENSE
  vendor/k8s.io/cli-runtime/pkg/printers/discard.go
  vendor/k8s.io/cli-runtime/pkg/printers/doc.go
  vendor/k8s.io/cli-runtime/pkg/printers/interface.go
  vendor/k8s.io/cli-runtime/pkg/printers/json.go
  vendor/k8s.io/cli-runtime/pkg/printers/jsonpath.go
  vendor/k8s.io/cli-runtime/pkg/printers/managedfields.go
  vendor/k8s.io/cli-runtime/pkg/printers/name.go
  vendor/k8s.io/cli-runtime/pkg/printers/sourcechecker.go
  vendor/k8s.io/cli-runtime/pkg/printers/tableprinter.go
  vendor/k8s.io/cli-runtime/pkg/printers/tabwriter.go
  vendor/k8s.io/cli-runtime/pkg/printers/template.go
  vendor/k8s.io/cli-runtime/pkg/printers/typesetter.go
  vendor/k8s.io/cli-runtime/pkg/printers/warningprinter.go
  vendor/k8s.io/cli-runtime/pkg/printers/yaml.go
  vendor/k8s.io/client-go/third_party/forked/golang/LICENSE
  vendor/k8s.io/client-go/third_party/forked/golang/PATENTS
  vendor/k8s.io/client-go/third_party/forked/golang/template/exec.go
  vendor/k8s.io/client-go/third_party/forked/golang/template/funcs.go
  vendor/k8s.io/client-go/util/jsonpath/doc.go
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/k8s.io/client-go/util/jsonpath/node.go
  vendor/k8s.io/client-go/util/jsonpath/parser.go
  vendor/modules.txt
Labels: kind/feature, size/XXL, release-note, cncf-cla: yes, lgtm, approved

#1504 Temporarily fix Ubuntu e2e tests
  hack/ci/Vagrantfile-ubuntu
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#1502 Reuse existing bpf code
  .golangci.yml
  Makefile
  internal/pkg/cli/recorder/bpf/recorder.bpf.c
  internal/pkg/cli/recorder/generate/main.go
  internal/pkg/cli/recorder/generated.go
  internal/pkg/cli/recorder/logsink.go
  internal/pkg/cli/recorder/recorder.go
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.c
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/generated.go
  internal/pkg/util/convert.go
  nix/derivation-bpf.nix
Labels: size/XXL, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#1509 Remove bpftool dependency
  Makefile
  nix/derivation-bpf.nix
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1507 Reuse original gpg key for Ubuntu e2e tests
  hack/ci/Vagrantfile-ubuntu
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#1503 Allow filtering command in ebpf code
  internal/pkg/cli/recorder/recorder.go
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.c
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/bpfrecorder/bpfrecorderfakes/fake_impl.go
  internal/pkg/daemon/bpfrecorder/generated.go
  internal/pkg/daemon/bpfrecorder/impl.go
Labels: kind/feature, size/XXL, cncf-cla: yes, lgtm, release-note-none, approved
