Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2023-07, with the labels that each got.

#1762 Update kustomize to v5.1.0
  Makefile
  dependencies.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1749 Bump kind to v0.20.0
  .github/workflows/olm_tests.yaml
  dependencies.yaml
  test/suite_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#1786 Remove the step which upgrades vagrant box in flatcar e2e tests
  .github/workflows/test.yml
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#1784 Use dependabot group for Kubernetes updates
  .github/dependabot.yml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1782 Switch to debian bookworm for build base image
  Dockerfile.build-image
  dependencies.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1796 Update CRI-O to v1.27.1
  dependencies.yaml
  hack/ci/install-cri-o.sh
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#1803 Deflake enricher unit tests
  internal/pkg/cli/runner/impl.go
  internal/pkg/cli/runner/runner.go
  internal/pkg/cli/runner/runner_test.go
  internal/pkg/cli/runner/runnerfakes/fake_impl.go
Labels: cncf-cla: yes, kind/flake, lgtm, release-note-none, approved, size/M
