Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2024-11, with the labels that each got.

#2551 Update third party dependencies
  .github/workflows/build.yml
  .github/workflows/olm_tests.yaml
  Dockerfile.build-image
  Makefile
  PROJECT
  bundle.Dockerfile
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  cloudbuild.yaml
  dependencies.yaml
  deploy/base/clusterserviceversion.yaml
  deploy/helm/templates/deployment.yaml
  deploy/kustomize-deployment/manager_deployment.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  hack/ci/Vagrantfile-debian
  hack/ci/Vagrantfile-ubuntu
  hack/ci/e2e-olm.sh
  hack/ci/install-yq.sh
  hack/install-libbpf.sh
  internal/pkg/manager/spod/bindata/spod.go
Labels: release-note, cncf-cla: yes, lgtm, approved, kind/cleanup, size/M

#2552 Bump UBI images
  Dockerfile.ubi
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#2553 Build amd64 and arm64 platforms for build image
  .github/workflows/build.yml
  Dockerfile.build-image
Labels: cncf-cla: yes, kind/failing-test, size/S, lgtm, release-note-none, approved

#2558 Fix build image target arch and tag
  .github/workflows/build.yml
  Dockerfile.build-image
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/M

#2560 Don't use docker buildx
  .github/workflows/build.yml
  Dockerfile.build-image
  dependencies.yaml
  hack/image-cross.sh
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/M

#2554 AppArmor: Add read permission for executables
  examples/apparmorprofile-sleep.yaml
  internal/pkg/daemon/apparmorprofile/crd2armor/crd2armor.go
Labels: kind/bug, release-note, cncf-cla: yes, ok-to-test, lgtm, approved, size/XS

#2565 Ignore `exit` syscall for runc base profile
  hack/ci/e2e-seccomp.sh
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#2571 Update runc to v1.2.2
  dependencies.yaml
  examples/baseprofile-runc.yaml
  hack/ci/Vagrantfile-debian
  hack/ci/Vagrantfile-ubuntu
  installation-usage.md
  test/tc_base_profiles_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M
