Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2024-02, with the labels that each got.

#2102 Install CRI-O and Podman side by side in Fedora tests
  hack/ci/Vagrantfile-fedora
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#2103 Update runc to 1.1.12
  dependencies.yaml
  examples/baseprofile-runc.yaml
  hack/ci/Vagrantfile-ubuntu
  installation-usage.md
  test/tc_base_profiles_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/documentation

#2114 Don't download runc manually
  dependencies.yaml
  hack/ci/Vagrantfile-ubuntu
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#2112 Bump test Kubernetes to v1.29
  .github/workflows/olm_tests.yaml
  dependencies.yaml
  hack/ci/Vagrantfile-fedora
  hack/ci/Vagrantfile-ubuntu
  test/suite_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#2117 Update golang to v1.22
  .github/workflows/build.yml
  .github/workflows/olm_tests.yaml
  .github/workflows/test.yml
  Makefile
  dependencies.yaml
  nix/derivation-bpf.nix
  nix/derivation.nix
  nix/nixpkgs.json
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#2124 Update crun to 1.14.1
  dependencies.yaml
  examples/baseprofile-crun.yaml
  test/tc_base_profiles_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/documentation

#2131 Minor Installation Documentation fixes
  installation-usage.md
Labels: cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, size/XS, kind/documentation
