Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2024-08, with the labels that each got.

#2406 Switch to latest crun (again)
  dependencies.yaml
  examples/baseprofile-crun.yaml
  hack/install-crun
  test/tc_base_profiles_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#2416 Update golangci-lint to v1.60.2
  .golangci.yml
  Makefile
  dependencies.yaml
  test/tc_apparmor_base_usage_test.go
  test/tc_webhook_config_test.go
Labels: cncf-cla: yes, kind/failing-test, size/S, lgtm, release-note-none, approved

#2413 Switch to go 1.23
  .github/workflows/build.yml
  .github/workflows/olm_tests.yaml
  .github/workflows/test.yml
  Makefile
  dependencies.yaml
  go.mod
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#2417 Fix `as` -> `AS` syntax
  Dockerfile
  Dockerfile.ubi
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#2412 `spoc record`: drop sudo privileges
  cmd/spoc/main.go
  internal/pkg/cli/command/command.go
  internal/pkg/cli/command/commandfakes/fake_impl.go
  internal/pkg/cli/command/consts.go
  internal/pkg/cli/command/impl.go
  internal/pkg/cli/command/options.go
  internal/pkg/cli/recorder/consts.go
  test/spoc/demobinary.go
  test/spoc/e2e_spoc_test.go
Labels: kind/feature, size/L, release-note, cncf-cla: yes, ok-to-test, lgtm, approved

#2422 Vagrant: switch to Fedora 39
  dependencies.yaml
  hack/ci/Vagrantfile-fedora
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#2421 apparmor recorder: add hugepage support
  internal/pkg/daemon/bpfrecorder/bpfrecorder_apparmor.go
  test/spoc/demobinary.go
  test/spoc/e2e_spoc_test.go
Labels: kind/bug, release-note, cncf-cla: yes, ok-to-test, lgtm, approved, size/M
