Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2024-07, with the labels that each got.

#2333 `spoc record --no-proc`: include all namespaces
  internal/pkg/cli/recorder/impl.go
  internal/pkg/cli/recorder/recorder.go
  internal/pkg/cli/recorder/recorderfakes/fake_impl.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_apparmor.go
  internal/pkg/util/process.go
  internal/pkg/util/process_test.go
  test/spoc/e2e_spoc_test.go
Labels: size/L, cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, kind/cleanup

#2339 Update golangci-lint and fix lints
  .golangci.yml
  Makefile
  dependencies.yaml
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/metrics/metrics_test.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/manager/nodestatus/nodestatus.go
  internal/pkg/manager/spod/spod_controller.go
  internal/pkg/manager/workloadannotator/setup.go
  test/tc_bpf_recorder_test.go
  test/tc_log_enricher_test.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#2344 Enable and fix `testifylint` linter
  .golangci.yml
  internal/pkg/artifact/artifact_test.go
  internal/pkg/artifact/profile_reader_test.go
  internal/pkg/cli/command/options_test.go
  internal/pkg/cli/converter/converter_test.go
  internal/pkg/cli/converter/options_test.go
  internal/pkg/cli/merger/merger_test.go
  internal/pkg/cli/merger/options_test.go
  internal/pkg/cli/platform_test.go
  internal/pkg/cli/puller/options_test.go
  internal/pkg/cli/pusher/options_test.go
  internal/pkg/cli/recorder/options_test.go
  internal/pkg/cli/recorder/recorder_test.go
  internal/pkg/cli/runner/options_test.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/enricher/enricher_test.go
  internal/pkg/daemon/metrics/metrics_test.go
  internal/pkg/daemon/profilerecorder/profilerecorder_test.go
  internal/pkg/daemon/seccompprofile/seccompprofile_test.go
  internal/pkg/manager/recordingmerger/merge_utils_test.go
  internal/pkg/nonrootenabler/nonrootenabler_test.go
  internal/pkg/version/version_test.go
  internal/pkg/webhooks/binding/binding_test.go
  internal/pkg/webhooks/recording/recording_test.go
  internal/pkg/webhooks/utils/utils_test.go
  test/spoc/e2e_spoc_test.go
  test/suite_test.go
Labels: cncf-cla: yes, size/XL, lgtm, release-note-none, approved, kind/cleanup

#2358 Extend the apparmor e2e test to apply the recorded profile
  hack/ci/e2e-apparmor.sh
Labels: kind/bug, size/L, cncf-cla: yes, lgtm, release-note-none, approved

#2361 Fix CRI-O related runtime binary path
  hack/ci/Vagrantfile-fedora
  hack/ci/e2e-seccomp.sh
Labels: cncf-cla: yes, kind/failing-test, size/S, lgtm, release-note-none, approved

#2360 Use `.gitignore` in nix build excludes
  nix/derivation-bpf.nix
  nix/derivation.nix
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#2386 fix flaky recorder: use recorder pid to determine mntns
  internal/pkg/cli/recorder/recorder.go
Labels: kind/bug, cncf-cla: yes, needs-ok-to-test, kind/flake, lgtm, release-note-none, approved, size/XS
