Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2024-05, with the labels that each got.

#2231 Enable and fix `perfsprint` linter
  .golangci.yml
  cmd/security-profiles-operator/main.go
  internal/pkg/artifact/artifact.go
  internal/pkg/daemon/apparmorprofile/apparmorprofile.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/metrics/metrics.go
  internal/pkg/daemon/metrics/metrics_test.go
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/seccompprofile/seccompprofile_test.go
  internal/pkg/daemon/selinuxprofile/common_controller.go
  internal/pkg/manager/recordingmerger/merge_utils.go
  internal/pkg/manager/recordingmerger/recordingmerger.go
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/spod_controller.go
  internal/pkg/util/names.go
  internal/pkg/version/version.go
  internal/pkg/webhooks/utils/utils.go
  test/e2e_test.go
  test/spoc/e2e_spoc_test.go
  test/suite_test.go
  test/tc_bpf_recorder_test.go
  test/tc_profilemerging_test.go
  test/tc_profilerecordings_test.go
  test/tc_profiling_test.go
  test/tc_seccomp_profilebindings_test.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#2242 Update crun to 1.15
  dependencies.yaml
  examples/baseprofile-crun.yaml
  hack/install-crun
  test/tc_base_profiles_test.go
Labels: cncf-cla: yes, release-note-none, approved, size/XS, kind/cleanup

#2145 fix: dynamic clusters sometimes encounter a finalizer mismatch
  internal/pkg/manager/nodestatus/nodestatus.go
  internal/pkg/util/nodeutils.go
Labels: kind/bug, size/L, cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, do-not-merge/contains-merge-commits

#2240 `spoc merge`: add `--check`
  cmd/spoc/main.go
  internal/pkg/cli/merger/consts.go
  internal/pkg/cli/merger/merger.go
  internal/pkg/cli/merger/options.go
Labels: kind/feature, release-note, cncf-cla: yes, ok-to-test, lgtm, approved, size/M

#2239 AppArmor: support path globs when merging profiles
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/manager/recordingmerger/apparmor.go
  internal/pkg/manager/recordingmerger/apparmor_test.go
  internal/pkg/manager/recordingmerger/merge_utils.go
  internal/pkg/manager/recordingmerger/merge_utils_test.go
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, ok-to-test, lgtm, approved

#2258 Update debian-base to v1.0.3
  Dockerfile.build-image
  dependencies.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#2263 Bump kind and zeitgeist to their latest releases
  .github/workflows/olm_tests.yaml
  Makefile
  dependencies.yaml
  test/suite_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup
