Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2024-12, with the labels that each got.

#2594 Fix CNI config in CI
  hack/ci/Vagrantfile-debian
  hack/ci/Vagrantfile-fedora
  hack/ci/Vagrantfile-ubuntu
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#2599 Remove file from known read files prefixes
  internal/pkg/daemon/bpfrecorder/apparmor_filters.go
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#2606 Clean up and structure the README
  README.md
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation, size/M

#2610 Update crun to 1.19
  dependencies.yaml
  examples/apparmorprofile-sleep.yaml
  examples/baseprofile-crun.yaml
  hack/install-crun
  test/tc_base_profiles_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#2612 Overwrite only some settings in the security context when apparmor is enabled
  internal/pkg/manager/spod/spod_controller.go
Labels: kind/bug, release-note, cncf-cla: yes, size/S, lgtm, approved

#2618 Update runc to v1.2.3
  dependencies.yaml
  examples/baseprofile-runc.yaml
  installation-usage.md
  test/tc_base_profiles_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#2624 Add `chroot` to runc baseprofile
  examples/apparmorprofile-sleep.yaml
  examples/baseprofile-runc.yaml
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/XS

#2643 Update Kubernetes in CI to v1.32.0
  .github/workflows/olm_tests.yaml
  dependencies.yaml
  hack/ci/Vagrantfile-debian
  hack/ci/Vagrantfile-fedora
  hack/ci/Vagrantfile-ubuntu
  test/suite_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup
