Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2024-06, with the labels that each got.

#2282 Bump to v0.8.4
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/base/clusterserviceversion.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#2285 Back to dev
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/back-to-dev.sh
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  release.md
  test/e2e_test.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/documentation

#2290 Switch to cert-manager v1.15.0
  dependencies.yaml
  hack/ci/baseprofiles.sh
  hack/ci/e2e-olm.sh
  installation-usage.md
  test/e2e_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#2297 Docs: Fix `enableAppArmor` variable
  installation-usage.md
Labels: release-note, cncf-cla: yes, lgtm, approved, size/XS, kind/documentation

#2299 Make selinuxd images configurable
  bundle/manifests/security-profiles-operator-profile_v1_configmap.yaml
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  deploy/base/profiles/selinuxd-image-mapping.json
  deploy/helm/templates/deployment.yaml
  deploy/helm/templates/static-resources.yaml
  deploy/helm/values.yaml
  deploy/kustomize-deployment/manager_deployment.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
Labels: kind/feature, release-note, cncf-cla: yes, ok-to-test, lgtm, approved, size/M

#2298 Docs: Hint that SELinux can be enabled/disabled
  installation-usage.md
Labels: release-note, cncf-cla: yes, lgtm, approved, size/XS, kind/documentation

#2311 Bump runc to v1.1.13
  dependencies.yaml
  examples/baseprofile-runc.yaml
  installation-usage.md
  test/tc_base_profiles_test.go
Labels: release-note, cncf-cla: yes, lgtm, approved, kind/cleanup, size/M

#2318 Update nixpkgs
  internal/pkg/daemon/bpfrecorder/generated.go
  nix/nixpkgs.json
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup
