Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2025-03, with the labels that each got.

#2757 Use golang from go.mod and switch to 1.24
  .github/workflows/build.yml
  .github/workflows/olm_tests.yaml
  .github/workflows/test.yml
  Makefile
  dependencies.yaml
  go.mod
  internal/pkg/artifact/artifact_test.go
  internal/pkg/daemon/apparmorprofile/apparmorprofile_test.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/profilerecorder/profilerecorder_test.go
  internal/pkg/daemon/seccompprofile/seccompprofile_test.go
  internal/pkg/daemon/selinuxprofile/selinuxprofile_test.go
  internal/pkg/webhooks/binding/binding_test.go
  internal/pkg/webhooks/recording/recording_test.go
  internal/pkg/webhooks/utils/utils_test.go
  nix/nixpkgs.json
  nix/overlay.nix
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#2771 Fix permission denied when loading apparmor profiles
  deploy/base/profiles/spo-apparmor.yaml
  deploy/helm/templates/static-resources.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
Labels: kind/bug, cncf-cla: yes, size/S, ok-to-test, lgtm, release-note-none, approved

#2779 Update runc to v1.2.6
  dependencies.yaml
  examples/baseprofile-runc.yaml
  installation-usage.md
  test/tc_base_profiles_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#2781 Fix ppc64le and exclude s390x builds
  Makefile
  hack/image-cross.sh
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_util_linux_s390x.go
  nix/nixpkgs.json
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#2787 Switch to golangci-lint v2
  .golangci.yml
  Makefile
  api/profilebase/v1alpha1/profilebase.go
  api/spod/v1alpha1/spod_types.go
  dependencies.yaml
  internal/pkg/cli/installer/options_test.go
  internal/pkg/cli/platform.go
  internal/pkg/daemon/bpfrecorder/generate/main.go
  internal/pkg/daemon/profilerecorder/profilerecorder.go
  internal/pkg/daemon/profilerecorder/profilerecorder_test.go
  internal/pkg/manager/spod/bindata/spod.go
  internal/pkg/manager/spod/spod_controller.go
  internal/pkg/manager/workloadannotator/workloadannotator.go
  internal/pkg/nonrootenabler/nonrootenabler.go
  internal/pkg/webhooks/binding/binding.go
  internal/pkg/webhooks/binding/binding_test.go
  internal/pkg/webhooks/recording/recording.go
  internal/pkg/webhooks/recording/recording_test.go
  test/suite_test.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#2788 Make nix-spoc builds a matrix
  .github/workflows/build.yml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M
