Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2025-05, with the labels that each got.

#2834 Update runc to v1.3.0
  dependencies.yaml
  examples/baseprofile-runc.yaml
  installation-usage.md
  test/tc_base_profiles_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#2842 Revert "Apply the seccomp and selinux profiles only there are actual changes"
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/selinuxprofile/selinuxprofile.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#2850 Update golangci-lint and config
  .golangci.yml
  Makefile
  dependencies.yaml
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#2847 Update kind to v0.27.0 and images
  .github/workflows/olm_tests.yaml
  dependencies.yaml
  test/suite_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#2848 Update Kubernetes in CI to v1.33.0
  dependencies.yaml
  hack/ci/Vagrantfile-debian
  hack/ci/Vagrantfile-fedora
  hack/ci/Vagrantfile-ubuntu
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#2849 Update cert-manager to v1.17.2
  dependencies.yaml
  hack/ci/e2e-olm.sh
  hack/ci/install-spo.sh
  installation-usage.md
  test/e2e_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/cleanup

#2852 Transition pjbgf to Emeritus status
  OWNERS
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup
