Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2025-04, with the labels that each got.

#2796 Allow individual controllers of manager to be turn on/off
  cmd/security-profiles-operator/main.go
Labels: kind/feature, release-note, cncf-cla: yes, ok-to-test, lgtm, approved, size/M

#2805 Bump to v0.9.1
  VERSION
  bundle/manifests/security-profiles-operator-profile_v1_configmap.yaml
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_apparmorprofiles.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_profilebindings.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_profilerecordings.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_rawselinuxprofiles.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_seccompprofiles.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_securityprofilenodestatuses.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_securityprofilesoperatordaemons.yaml
  bundle/manifests/security-profiles-operator.x-k8s.io_selinuxprofiles.yaml
  dependencies.yaml
  deploy/base/clusterserviceversion.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  test/e2e_test.go
Labels: size/L, cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup

#2806 Back to dev
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#2808 Fix the logging at the given verbosity
  cmd/security-profiles-operator/main.go
Labels: kind/bug, cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, size/XS

#2809 Fix permission denied when loading apparmor profiles
  bundle/manifests/security-profiles-operator-profile_v1_configmap.yaml
  deploy/base/profiles/spo-apparmor.yaml
  deploy/helm/templates/static-resources.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
Labels: kind/bug, cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, size/XS

#2813 Allow seccompprofile controller to be turned off in spod
  cmd/security-profiles-operator/main.go
Labels: kind/feature, cncf-cla: yes, size/S, ok-to-test, lgtm, release-note-none, approved

#2815 Update crun to 1.21
  dependencies.yaml
  examples/baseprofile-crun.yaml
  hack/install-crun
  test/tc_base_profiles_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#2816 Use Ubuntu 24.04 for tests
  .github/workflows/build.yml
  .github/workflows/olm_tests.yaml
  .github/workflows/test.yml
Labels: cncf-cla: yes, kind/failing-test, lgtm, release-note-none, approved, size/M

#2811 Process backlog before the new audit log to maintain ordering
  internal/pkg/daemon/enricher/enricher.go
  internal/pkg/daemon/enricher/enricher_test.go
Labels: kind/bug, cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, size/M

#2818 Switch to `beta` maturity
  bundle.Dockerfile
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  deploy/base/clusterserviceversion.yaml
Labels: release-note, cncf-cla: yes, size/S, lgtm, approved, kind/cleanup

#2827 install the profile before checking and creating node status
  internal/pkg/daemon/apparmorprofile/apparmorprofile.go
Labels: cncf-cla: yes, size/S, ok-to-test, lgtm, release-note-none, approved

#2826 Apply the seccomp and selinux profiles only there are actual changes
  internal/pkg/daemon/seccompprofile/seccompprofile.go
  internal/pkg/daemon/selinuxprofile/selinuxprofile.go
Labels: kind/bug, release-note, cncf-cla: yes, lgtm, approved, size/XS
