Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2025-02, with the labels that each got.

#2710 Fix profile install/uninstall path
  internal/pkg/daemon/apparmorprofile/apparmor_supported.go
Labels: kind/bug, release-note, cncf-cla: yes, needs-ok-to-test, size/S, lgtm, approved

#2713 AppArmor: Do not deny `mount`
  internal/pkg/daemon/apparmorprofile/crd2armor/crd2armor.go
Labels: kind/bug, release-note, cncf-cla: yes, size/S, ok-to-test, lgtm, approved

#2718 Add fsck.ext4 to the list of allowed executables when mount is allowed
  internal/pkg/daemon/apparmorprofile/crd2armor/crd2armor.go
Labels: kind/bug, cncf-cla: yes, lgtm, release-note-none, approved, size/XS

#2719 BPF Recorder: fix how we detect file types
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.c
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.o.amd64
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.o.arm64
Labels: kind/bug, cncf-cla: yes, needs-ok-to-test, size/S, lgtm, release-note-none, approved

#2720 Add /sbin/fsck to allowed executables when mount is active, and generalize the /sys/devices path
  internal/pkg/daemon/apparmorprofile/crd2armor/crd2armor.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_apparmor.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_apparmor_test.go
Labels: kind/bug, cncf-cla: yes, size/S, lgtm, release-note-none, approved

#2725 Update crun to 1.20
  dependencies.yaml
  examples/baseprofile-crun.yaml
  hack/install-crun
  test/tc_base_profiles_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, size/XS, kind/cleanup

#2739 Update go to v1.24
  .github/workflows/build.yml
  .github/workflows/olm_tests.yaml
  .github/workflows/test.yml
  .golangci.yml
  Makefile
  dependencies.yaml
  internal/pkg/daemon/selinuxprofile/selinuxprofile_test.go
  internal/pkg/manager/spod/setup_test.go
Labels: cncf-cla: yes, size/S, lgtm, release-note-none, approved, kind/documentation

#2742 Bump to v0.9.0
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/base/clusterserviceversion.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#2740 Switch to new CRI-O package location
  dependencies.yaml
  examples/baseprofile-runc.yaml
  hack/ci/Vagrantfile-debian
  hack/ci/Vagrantfile-fedora
  hack/ci/Vagrantfile-ubuntu
  installation-usage.md
  test/tc_base_profiles_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#2743 Back to dev
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M

#2589 MULTIARCH-4654: Enabled the Security Profiles Operator for ppc64le
  Dockerfile.ubi
  bundle/manifests/security-profiles-operator-profile_v1_configmap.yaml
  deploy/base/clusterserviceversion.yaml
  deploy/base/profiles/bpf-recorder.json
  deploy/base/profiles/security-profiles-operator.json
  deploy/helm/templates/static-resources.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  hack/image-cross.sh
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_util_default.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_util_linux_ppc64le.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_util_linux_s390x.go
  test/e2e_test.go
Labels: kind/feature, release-note, cncf-cla: yes, size/XL, ok-to-test, lgtm, approved
