Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2025-08, with the labels that each got.

#2954 2940: optionally enable TLS 1.3 for SPO webhook
  cmd/security-profiles-operator/main.go
  internal/pkg/util/enum.go
  internal/pkg/util/enum_test.go
Labels: size/L, release-note, cncf-cla: yes, ok-to-test, lgtm, approved

#2966 Add webhook options only for openshift deployments to handle node debugging label
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/overlays/openshift-dev/kustomization.yaml
  deploy/overlays/openshift-downstream/kustomization.yaml
Labels: kind/feature, cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, size/M

#2967 Switch to clang 19
  dependencies.yaml
  hack/pull-security-profiles-operator-verify
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.o.amd64
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.o.arm64
  internal/pkg/daemon/bpfrecorder/vmlinux/arm64/vmlinux.h
  internal/pkg/daemon/bpfrecorder/vmlinux/x86/vmlinux.h
  internal/pkg/daemon/enricher/auditsource/bpf/enricher.bpf.o.amd64
  internal/pkg/daemon/enricher/auditsource/bpf/enricher.bpf.o.arm64
  nix/derivation-bpf.nix
  nix/nixpkgs.json
Labels: cncf-cla: yes, size/XL, lgtm, release-note-none, approved, kind/cleanup

#2975 Back to dev
  VERSION
  bundle/manifests/security-profiles-operator.clusterserviceversion.yaml
  dependencies.yaml
  deploy/catalog-preamble.json
  deploy/helm/Chart.yaml
  deploy/kustomize-deployment/kustomization.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  examples/olm/install-resources.yaml
  hack/ci/e2e-olm.sh
  hack/deploy-localhost.patch
  test/e2e_test.go
Labels: cncf-cla: yes, lgtm, release-note-none, approved, kind/cleanup, size/M
