Repository kubernetes-sigs/security-profiles-operator, pull requests merged in 2025-01, with the labels that each got.

#2657 BPF Recorder: Serialize event processing
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
Labels: kind/feature, cncf-cla: yes, needs-ok-to-test, size/S, lgtm, release-note-none, approved

#2664 Simplify CI Scripts
  examples/apparmorprofile-sleep-complain-mode.yaml
  hack/ci/e2e-apparmor.sh
  hack/ci/e2e-seccomp.sh
  hack/ci/install-spo.sh
Labels: size/L, cncf-cla: yes, needs-ok-to-test, lgtm, release-note-none, approved, kind/cleanup

#2675 BPF Recorder: load bpf program on startup to win race with container startup
  examples/apparmorprofile-sleep-crun.yaml
  internal/pkg/cli/recorder/impl.go
  internal/pkg/cli/recorder/recorder.go
  internal/pkg/cli/recorder/recorderfakes/fake_impl.go
  internal/pkg/daemon/bpfrecorder/bpf_program_collection.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_apparmor.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_seccomp.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_test.go
  internal/pkg/daemon/bpfrecorder/bpfrecorderfakes/fake_impl.go
  internal/pkg/daemon/bpfrecorder/impl.go
  internal/pkg/daemon/bpfrecorder/vars.go
Labels: cncf-cla: yes, size/XL, kind/flake, ok-to-test, lgtm, release-note-none, approved

#2667 bpf: add `path_unlink` hook
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.c
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.o.amd64
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.o.arm64
  internal/pkg/daemon/bpfrecorder/bpfrecorder_apparmor.go
  test/spoc/demobinary.go
  test/spoc/e2e_spoc_test.go
Labels: kind/feature, release-note, cncf-cla: yes, ok-to-test, lgtm, approved, size/M

#2682 BPF Recorder: clean up bpf logging
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.c
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.o.amd64
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.o.arm64
Labels: cncf-cla: yes, needs-ok-to-test, lgtm, release-note-none, approved, kind/cleanup, size/M

#2688 bpf-recorder needs /sys/kernel/tracing/events/raw_syscalls/sys_enter/id
  internal/pkg/manager/spod/bindata/spod.go
Labels: kind/bug, cncf-cla: yes, size/S, ok-to-test, lgtm, release-note-none, approved

#2690 BPF Recorder: Prune runc container startup more agressively
  examples/apparmorprofile-sleep-crun.yaml
  examples/apparmorprofile-sleep-runc.yaml
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.c
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.o.amd64
  internal/pkg/daemon/bpfrecorder/bpf/recorder.bpf.o.arm64
  internal/pkg/daemon/bpfrecorder/bpfrecorder.go
Labels: kind/feature, cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved, size/M

#2696 fix apparmor profile for spod
  deploy/base/profiles/bpfrecorder-apparmor.yaml
  deploy/base/profiles/spo-apparmor.yaml
  deploy/helm/templates/static-resources.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
Labels: kind/bug, size/L, cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved

#2698 Make AppArmor Recording work with AppArmor Profile
  deploy/base/profiles/spo-apparmor.yaml
  deploy/helm/templates/static-resources.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
Labels: kind/bug, size/L, cncf-cla: yes, ok-to-test, lgtm, release-note-none, approved

#2701 Make AppArmor recording actually work
  deploy/base/profiles/spo-apparmor.yaml
  deploy/helm/templates/static-resources.yaml
  deploy/namespace-operator.yaml
  deploy/openshift-dev.yaml
  deploy/openshift-downstream.yaml
  deploy/operator.yaml
  deploy/webhook-operator.yaml
  internal/pkg/daemon/apparmorprofile/crd2armor/crd2armor.go
Labels: kind/bug, cncf-cla: yes, needs-ok-to-test, size/S, lgtm, release-note-none, approved

#2702 apparmor recorder: generalize random digit sequences
  internal/pkg/daemon/bpfrecorder/bpfrecorder_apparmor.go
  internal/pkg/daemon/bpfrecorder/bpfrecorder_apparmor_test.go
  test/spoc/e2e_spoc_test.go
Labels: kind/feature, release-note, cncf-cla: yes, size/S, ok-to-test, lgtm, approved
